// ============================================
// FACTORY DOMINION: AUTOMATED EMPIRE
// Game Data Definitions
// ============================================

import { BuildingDefinition, TransportDefinition, WorkerDefinition, ResearchNode, MarketPrice, AutomationUnlock, PrestigeBonus, ResourceType, MegaProject, DailyReward, WeatherType, WeatherDefinition, Quest } from './types';

// --- Resource Metadata ---
export const RESOURCE_META: Record<ResourceType, { name: string; emoji: string; tier: number; color: string }> = {
  // Raw
  iron: { name: 'Iron Ore', emoji: '⛏️', tier: 0, color: '#a0a0a0' },
  copper: { name: 'Copper Ore', emoji: '🟤', tier: 0, color: '#b87333' },
  coal: { name: 'Coal', emoji: '🖤', tier: 0, color: '#333333' },
  oil: { name: 'Crude Oil', emoji: '🛢️', tier: 0, color: '#1a1a2e' },
  sand: { name: 'Sand', emoji: '🏖️', tier: 0, color: '#c2b280' },
  lithium: { name: 'Lithium', emoji: '💎', tier: 0, color: '#7b68ee' },
  water: { name: 'Water', emoji: '💧', tier: 0, color: '#4488ff' },
  rareEarth: { name: 'Rare Earth', emoji: '✨', tier: 0, color: '#9932cc' },
  // Tier 1
  ironPlate: { name: 'Iron Plate', emoji: '🔩', tier: 1, color: '#c0c0c0' },
  copperWire: { name: 'Copper Wire', emoji: '🔌', tier: 1, color: '#daa520' },
  plastic: { name: 'Plastic', emoji: '🧴', tier: 1, color: '#ff6b6b' },
  glass: { name: 'Glass', emoji: '🪟', tier: 1, color: '#87ceeb' },
  carbon: { name: 'Carbon Fiber', emoji: '🖤', tier: 1, color: '#2d2d2d' },
  // Tier 2
  circuit: { name: 'Circuit Board', emoji: '💚', tier: 2, color: '#00cc66' },
  engine: { name: 'Engine', emoji: '🔧', tier: 2, color: '#ff8c00' },
  battery: { name: 'Battery', emoji: '🔋', tier: 2, color: '#32cd32' },
  gear: { name: 'Gear', emoji: '⚙️', tier: 2, color: '#808080' },
  steel: { name: 'Steel', emoji: '🛡️', tier: 2, color: '#708090' },
  // Tier 3
  aiChip: { name: 'AI Chip', emoji: '🧠', tier: 3, color: '#00ffff' },
  robotics: { name: 'Robotics', emoji: '🤖', tier: 3, color: '#ff69b4' },
  quantumPart: { name: 'Quantum Part', emoji: '⚛️', tier: 3, color: '#9400d3' },
  advancedAlloy: { name: 'Adv. Alloy', emoji: '💠', tier: 3, color: '#4169e1' },
  nanoMaterial: { name: 'Nano Material', emoji: '🔮', tier: 3, color: '#ff1493' },
};

// --- Building Definitions ---
export const BUILDING_DEFS: Record<string, BuildingDefinition> = {
  // Extractors
  miningDrill: {
    type: 'miningDrill',
    name: 'Mining Drill',
    description: 'Extracts raw minerals from the earth',
    category: 'extractor',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 500 }],
    costMultiplier: 1.15,
    basePowerConsumption: 5,
    basePowerProduction: 0,
    baseProductionRate: 2,
    outputs: [{ resource: 'iron', amount: 1 }, { resource: 'copper', amount: 0.3 }, { resource: 'coal', amount: 0.5 }],
    emoji: '⛏️',
  },
  oilPump: {
    type: 'oilPump',
    name: 'Oil Pump',
    description: 'Pumps crude oil from underground reserves',
    category: 'extractor',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 800 }],
    costMultiplier: 1.2,
    basePowerConsumption: 8,
    basePowerProduction: 0,
    baseProductionRate: 1.5,
    outputs: [{ resource: 'oil', amount: 1 }],
    emoji: '🛢️',
  },
  waterExtractor: {
    type: 'waterExtractor',
    name: 'Water Extractor',
    description: 'Extracts and purifies water from the environment',
    category: 'extractor',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 300 }],
    costMultiplier: 1.1,
    basePowerConsumption: 3,
    basePowerProduction: 0,
    baseProductionRate: 3,
    outputs: [{ resource: 'water', amount: 1 }],
    emoji: '💧',
  },
  quarry: {
    type: 'quarry',
    name: 'Quarry',
    description: 'Mines sand, lithium, and rare earth elements',
    category: 'extractor',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 1200 }],
    costMultiplier: 1.25,
    basePowerConsumption: 10,
    basePowerProduction: 0,
    baseProductionRate: 1,
    outputs: [{ resource: 'sand', amount: 0.8 }, { resource: 'lithium', amount: 0.2 }, { resource: 'rareEarth', amount: 0.05 }],
    unlockRequirement: { level: 5 },
    emoji: '🏔️',
  },
  // Tier 1 Factories
  smelter: {
    type: 'smelter',
    name: 'Smelter',
    description: 'Smelts iron ore into iron plates and combines with carbon for steel',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 1000 }],
    costMultiplier: 1.15,
    basePowerConsumption: 10,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'iron', amount: 2 }],
    outputs: [{ resource: 'ironPlate', amount: 1 }],
    emoji: '🔥',
  },
  wireMill: {
    type: 'wireMill',
    name: 'Wire Mill',
    description: 'Draws copper ore into fine copper wire',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 800 }],
    costMultiplier: 1.15,
    basePowerConsumption: 8,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'copper', amount: 1.5 }],
    outputs: [{ resource: 'copperWire', amount: 1 }],
    emoji: '🔌',
  },
  chemicalPlant: {
    type: 'chemicalPlant',
    name: 'Chemical Plant',
    description: 'Processes oil into plastic and coal into carbon fiber',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 1500 }],
    costMultiplier: 1.2,
    basePowerConsumption: 12,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'oil', amount: 1.5 }],
    outputs: [{ resource: 'plastic', amount: 1 }],
    emoji: '🧪',
  },
  glassFurnace: {
    type: 'glassFurnace',
    name: 'Glass Furnace',
    description: 'Melts sand into glass panes',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 900 }],
    costMultiplier: 1.15,
    basePowerConsumption: 8,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'sand', amount: 2 }],
    outputs: [{ resource: 'glass', amount: 1 }],
    emoji: '🪟',
  },
  steelForge: {
    type: 'steelForge',
    name: 'Steel Forge',
    description: 'Forges iron plates and coal into strong steel alloys',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 1800 }],
    costMultiplier: 1.18,
    basePowerConsumption: 14,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'ironPlate', amount: 2 }, { resource: 'coal', amount: 1 }],
    outputs: [{ resource: 'steel', amount: 1 }],
    emoji: '🛡️',
  },
  carbonProcessor: {
    type: 'carbonProcessor',
    name: 'Carbon Processor',
    description: 'Processes coal into high-grade carbon fiber for advanced manufacturing',
    category: 'factory',
    tier: 1,
    baseCost: [{ resource: 'money', amount: 2000 }],
    costMultiplier: 1.2,
    basePowerConsumption: 12,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'coal', amount: 3 }],
    outputs: [{ resource: 'carbon', amount: 1 }],
    emoji: '🖤',
  },
  // Tier 2 Factories
  gearFactory: {
    type: 'gearFactory',
    name: 'Gear Factory',
    description: 'Manufactures precision gears from iron plates',
    category: 'factory',
    tier: 2,
    baseCost: [{ resource: 'money', amount: 3000 }],
    costMultiplier: 1.2,
    basePowerConsumption: 15,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'ironPlate', amount: 2 }],
    outputs: [{ resource: 'gear', amount: 1 }],
    unlockRequirement: { research: 'basicMachining' },
    emoji: '⚙️',
  },
  circuitFactory: {
    type: 'circuitFactory',
    name: 'Circuit Factory',
    description: 'Assembles circuit boards from copper wire and plastic',
    category: 'factory',
    tier: 2,
    baseCost: [{ resource: 'money', amount: 5000 }],
    costMultiplier: 1.2,
    basePowerConsumption: 20,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'copperWire', amount: 2 }, { resource: 'plastic', amount: 1 }],
    outputs: [{ resource: 'circuit', amount: 1 }],
    unlockRequirement: { research: 'electronics' },
    emoji: '💚',
  },
  engineFactory: {
    type: 'engineFactory',
    name: 'Engine Factory',
    description: 'Builds powerful engines from gears and steel',
    category: 'factory',
    tier: 2,
    baseCost: [{ resource: 'money', amount: 8000 }],
    costMultiplier: 1.25,
    basePowerConsumption: 25,
    basePowerProduction: 0,
    baseProductionRate: 0.8,
    inputs: [{ resource: 'gear', amount: 3 }, { resource: 'steel', amount: 2 }],
    outputs: [{ resource: 'engine', amount: 1 }],
    unlockRequirement: { research: 'mechanicalEngineering' },
    emoji: '🔧',
  },
  batteryFactory: {
    type: 'batteryFactory',
    name: 'Battery Factory',
    description: 'Produces batteries from lithium and carbon fiber',
    category: 'factory',
    tier: 2,
    baseCost: [{ resource: 'money', amount: 6000 }],
    costMultiplier: 1.2,
    basePowerConsumption: 18,
    basePowerProduction: 0,
    baseProductionRate: 1,
    inputs: [{ resource: 'lithium', amount: 2 }, { resource: 'carbon', amount: 1 }],
    outputs: [{ resource: 'battery', amount: 1 }],
    unlockRequirement: { research: 'energyStorage' },
    emoji: '🔋',
  },
  // Tier 3 Factories
  aiLab: {
    type: 'aiLab',
    name: 'AI Lab',
    description: 'Creates advanced AI chips from circuits and batteries',
    category: 'factory',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 25000 }],
    costMultiplier: 1.3,
    basePowerConsumption: 50,
    basePowerProduction: 0,
    baseProductionRate: 0.5,
    inputs: [{ resource: 'circuit', amount: 3 }, { resource: 'battery', amount: 2 }],
    outputs: [{ resource: 'aiChip', amount: 1 }],
    unlockRequirement: { research: 'artificialIntelligence' },
    emoji: '🧠',
  },
  roboticsBay: {
    type: 'roboticsBay',
    name: 'Robotics Bay',
    description: 'Assembles robotic units from AI chips and engines',
    category: 'factory',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 40000 }],
    costMultiplier: 1.3,
    basePowerConsumption: 60,
    basePowerProduction: 0,
    baseProductionRate: 0.3,
    inputs: [{ resource: 'aiChip', amount: 2 }, { resource: 'engine', amount: 2 }],
    outputs: [{ resource: 'robotics', amount: 1 }],
    unlockRequirement: { research: 'roboticsTech' },
    emoji: '🤖',
  },
  quantumLab: {
    type: 'quantumLab',
    name: 'Quantum Lab',
    description: 'Produces quantum components using AI chips and rare earth',
    category: 'factory',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 100000 }],
    costMultiplier: 1.4,
    basePowerConsumption: 100,
    basePowerProduction: 0,
    baseProductionRate: 0.2,
    inputs: [{ resource: 'aiChip', amount: 3 }, { resource: 'rareEarth', amount: 5 }],
    outputs: [{ resource: 'quantumPart', amount: 1 }],
    unlockRequirement: { research: 'quantumPhysics' },
    emoji: '⚛️',
  },
  alloyForge: {
    type: 'alloyForge',
    name: 'Alloy Forge',
    description: 'Forges advanced alloys from steel and lithium',
    category: 'factory',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 35000 }],
    costMultiplier: 1.3,
    basePowerConsumption: 40,
    basePowerProduction: 0,
    baseProductionRate: 0.5,
    inputs: [{ resource: 'steel', amount: 3 }, { resource: 'lithium', amount: 2 }],
    outputs: [{ resource: 'advancedAlloy', amount: 1 }],
    unlockRequirement: { research: 'advancedMetallurgy' },
    emoji: '💠',
  },
  nanoLab: {
    type: 'nanoLab',
    name: 'Nano Lab',
    description: 'Synthesizes nano materials from advanced alloys and quantum parts',
    category: 'factory',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 200000 }],
    costMultiplier: 1.5,
    basePowerConsumption: 150,
    basePowerProduction: 0,
    baseProductionRate: 0.1,
    inputs: [{ resource: 'advancedAlloy', amount: 2 }, { resource: 'quantumPart', amount: 1 }],
    outputs: [{ resource: 'nanoMaterial', amount: 1 }],
    unlockRequirement: { research: 'nanotechnology' },
    emoji: '🔮',
  },
  // Power Plants
  coalGenerator: {
    type: 'coalGenerator',
    name: 'Coal Generator',
    description: 'Burns coal to generate electricity. Reliable but dirty.',
    category: 'power',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 400 }],
    costMultiplier: 1.15,
    basePowerConsumption: 0,
    basePowerProduction: 20,
    baseProductionRate: 1,
    fuel: 'coal',
    fuelRate: 0.5,
    emoji: '🏭',
  },
  solarPanel: {
    type: 'solarPanel',
    name: 'Solar Panel',
    description: 'Clean energy from the sun. Low output but free fuel.',
    category: 'power',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 600 }],
    costMultiplier: 1.1,
    basePowerConsumption: 0,
    basePowerProduction: 8,
    baseProductionRate: 1,
    emoji: '☀️',
  },
  windTurbine: {
    type: 'windTurbine',
    name: 'Wind Turbine',
    description: 'Harnesses wind power. Variable output.',
    category: 'power',
    tier: 0,
    baseCost: [{ resource: 'money', amount: 800 }],
    costMultiplier: 1.1,
    basePowerConsumption: 0,
    basePowerProduction: 12,
    baseProductionRate: 1,
    emoji: '🌀',
  },
  nuclearReactor: {
    type: 'nuclearReactor',
    name: 'Nuclear Reactor',
    description: 'Massive power output. Expensive to build.',
    category: 'power',
    tier: 2,
    baseCost: [{ resource: 'money', amount: 15000 }],
    costMultiplier: 1.3,
    basePowerConsumption: 0,
    basePowerProduction: 100,
    baseProductionRate: 1,
    unlockRequirement: { research: 'nuclearPower' },
    emoji: '☢️',
  },
  fusionReactor: {
    type: 'fusionReactor',
    name: 'Fusion Reactor',
    description: 'The pinnacle of energy technology. Limitless clean power.',
    category: 'power',
    tier: 3,
    baseCost: [{ resource: 'money', amount: 100000 }],
    costMultiplier: 1.5,
    basePowerConsumption: 0,
    basePowerProduction: 500,
    baseProductionRate: 1,
    unlockRequirement: { research: 'fusionEnergy' },
    emoji: '🌟',
  },
};

// --- Transport Definitions ---
export const TRANSPORT_DEFS: Record<string, TransportDefinition> = {
  conveyorBelt: {
    type: 'conveyorBelt',
    name: 'Conveyor Belt',
    description: 'Basic automated belt system for moving materials',
    baseCost: [{ resource: 'money', amount: 100 }],
    baseThroughput: 5,
    upgradeMultiplier: 1.5,
    emoji: '➡️',
  },
  pipe: {
    type: 'pipe',
    name: 'Pipe',
    description: 'Transports liquids and gases between buildings',
    baseCost: [{ resource: 'money', amount: 80 }],
    baseThroughput: 8,
    upgradeMultiplier: 1.4,
    emoji: '🔧',
  },
  truck: {
    type: 'truck',
    name: 'Truck',
    description: 'Motorized transport for medium loads',
    baseCost: [{ resource: 'money', amount: 500 }],
    baseThroughput: 15,
    upgradeMultiplier: 1.6,
    emoji: '🚚',
  },
  cargoTrain: {
    type: 'cargoTrain',
    name: 'Cargo Train',
    description: 'High-capacity rail transport system',
    baseCost: [{ resource: 'money', amount: 2000 }],
    baseThroughput: 40,
    upgradeMultiplier: 1.7,
    emoji: '🚂',
  },
  drone: {
    type: 'drone',
    name: 'Drone',
    description: 'Fast aerial transport for small loads',
    baseCost: [{ resource: 'money', amount: 3000 }],
    baseThroughput: 10,
    upgradeMultiplier: 1.5,
    emoji: '🚁',
  },
  cargoShip: {
    type: 'cargoShip',
    name: 'Cargo Ship',
    description: 'Massive maritime transport for bulk materials',
    baseCost: [{ resource: 'money', amount: 8000 }],
    baseThroughput: 80,
    upgradeMultiplier: 1.8,
    emoji: '🚢',
  },
};

// --- Research Tree ---
export const RESEARCH_TREE: ResearchNode[] = [
  // Automation Tier 1
  {
    id: 'basicAutomation',
    name: 'Basic Automation',
    description: '+15% production speed for all extractors',
    category: 'automation',
    tier: 1,
    cost: 50,
    timeRequired: 30,
    prerequisites: [],
    effects: [{ type: 'productionSpeed', target: 'extractor', value: 0.15 }],
    emoji: '🤖',
  },
  {
    id: 'advancedAutomation',
    name: 'Advanced Automation',
    description: '+25% production speed for all factories',
    category: 'automation',
    tier: 2,
    cost: 200,
    timeRequired: 60,
    prerequisites: ['basicAutomation'],
    effects: [{ type: 'productionSpeed', target: 'factory', value: 0.25 }],
    emoji: '🦾',
  },
  {
    id: 'basicMachining',
    name: 'Basic Machining',
    description: 'Unlocks Gear Factory',
    category: 'automation',
    tier: 1,
    cost: 100,
    timeRequired: 45,
    prerequisites: [],
    effects: [{ type: 'unlockBuilding', target: 'gearFactory', value: 1 }],
    emoji: '⚙️',
  },
  // Logistics
  {
    id: 'logistics1',
    name: 'Efficient Transport',
    description: '+20% transport throughput for all lines',
    category: 'logistics',
    tier: 1,
    cost: 75,
    timeRequired: 40,
    prerequisites: [],
    effects: [{ type: 'transportSpeed', value: 0.2 }],
    emoji: '🚚',
  },
  {
    id: 'advancedLogistics',
    name: 'Advanced Logistics',
    description: '+30% transport throughput, unlock Cargo Train',
    category: 'logistics',
    tier: 2,
    cost: 300,
    timeRequired: 80,
    prerequisites: ['logistics1'],
    effects: [{ type: 'transportSpeed', value: 0.3 }, { type: 'unlockTransport', target: 'cargoTrain', value: 1 }],
    emoji: '🚂',
  },
  // Energy
  {
    id: 'energyEfficiency',
    name: 'Energy Efficiency',
    description: '-15% power consumption for all buildings',
    category: 'energy',
    tier: 1,
    cost: 60,
    timeRequired: 35,
    prerequisites: [],
    effects: [{ type: 'powerEfficiency', value: 0.15 }],
    emoji: '⚡',
  },
  {
    id: 'nuclearPower',
    name: 'Nuclear Power',
    description: 'Unlocks Nuclear Reactor',
    category: 'energy',
    tier: 2,
    cost: 500,
    timeRequired: 120,
    prerequisites: ['energyEfficiency'],
    effects: [{ type: 'unlockBuilding', target: 'nuclearReactor', value: 1 }],
    emoji: '☢️',
  },
  {
    id: 'fusionEnergy',
    name: 'Fusion Energy',
    description: 'Unlocks Fusion Reactor - limitless clean power',
    category: 'energy',
    tier: 3,
    cost: 2000,
    timeRequired: 300,
    prerequisites: ['nuclearPower', 'quantumPhysics'],
    effects: [{ type: 'unlockBuilding', target: 'fusionReactor', value: 1 }],
    emoji: '🌟',
  },
  // Electronics & AI
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Unlocks Circuit Factory',
    category: 'ai',
    tier: 1,
    cost: 150,
    timeRequired: 50,
    prerequisites: [],
    effects: [{ type: 'unlockBuilding', target: 'circuitFactory', value: 1 }],
    emoji: '💚',
  },
  {
    id: 'energyStorage',
    name: 'Energy Storage',
    description: 'Unlocks Battery Factory',
    category: 'ai',
    tier: 2,
    cost: 250,
    timeRequired: 70,
    prerequisites: ['electronics'],
    effects: [{ type: 'unlockBuilding', target: 'batteryFactory', value: 1 }],
    emoji: '🔋',
  },
  {
    id: 'artificialIntelligence',
    name: 'Artificial Intelligence',
    description: 'Unlocks AI Lab - the heart of advanced technology',
    category: 'ai',
    tier: 2,
    cost: 500,
    timeRequired: 100,
    prerequisites: ['electronics', 'energyStorage'],
    effects: [{ type: 'unlockBuilding', target: 'aiLab', value: 1 }],
    emoji: '🧠',
  },
  // Robotics
  {
    id: 'mechanicalEngineering',
    name: 'Mechanical Engineering',
    description: 'Unlocks Engine Factory',
    category: 'robotics',
    tier: 1,
    cost: 200,
    timeRequired: 60,
    prerequisites: ['basicMachining'],
    effects: [{ type: 'unlockBuilding', target: 'engineFactory', value: 1 }],
    emoji: '🔧',
  },
  {
    id: 'roboticsTech',
    name: 'Robotics Technology',
    description: 'Unlocks Robotics Bay',
    category: 'robotics',
    tier: 2,
    cost: 800,
    timeRequired: 150,
    prerequisites: ['artificialIntelligence', 'mechanicalEngineering'],
    effects: [{ type: 'unlockBuilding', target: 'roboticsBay', value: 1 }],
    emoji: '🤖',
  },
  {
    id: 'advancedMetallurgy',
    name: 'Advanced Metallurgy',
    description: 'Unlocks Alloy Forge',
    category: 'robotics',
    tier: 2,
    cost: 600,
    timeRequired: 100,
    prerequisites: ['basicMachining'],
    effects: [{ type: 'unlockBuilding', target: 'alloyForge', value: 1 }],
    emoji: '💠',
  },
  // Quantum
  {
    id: 'quantumPhysics',
    name: 'Quantum Physics',
    description: 'Unlocks Quantum Lab',
    category: 'quantum',
    tier: 3,
    cost: 1500,
    timeRequired: 200,
    prerequisites: ['artificialIntelligence'],
    effects: [{ type: 'unlockBuilding', target: 'quantumLab', value: 1 }],
    emoji: '⚛️',
  },
  {
    id: 'nanotechnology',
    name: 'Nanotechnology',
    description: 'Unlocks Nano Lab - the ultimate production facility',
    category: 'quantum',
    tier: 3,
    cost: 3000,
    timeRequired: 400,
    prerequisites: ['quantumPhysics', 'advancedMetallurgy'],
    effects: [{ type: 'unlockBuilding', target: 'nanoLab', value: 1 }],
    emoji: '🔮',
  },
  // Market & Bonuses
  {
    id: 'marketAnalysis',
    name: 'Market Analysis',
    description: '+20% better sell prices on the market',
    category: 'automation',
    tier: 1,
    cost: 100,
    timeRequired: 40,
    prerequisites: [],
    effects: [{ type: 'marketBonus', value: 0.2 }],
    emoji: '📈',
  },
  {
    id: 'workerTraining',
    name: 'Worker Training',
    description: '+25% worker efficiency across all workers',
    category: 'automation',
    tier: 2,
    cost: 300,
    timeRequired: 80,
    prerequisites: ['basicAutomation'],
    effects: [{ type: 'workerEfficiency', value: 0.25 }],
    emoji: '👷',
  },
  {
    id: 'storageExpansion',
    name: 'Storage Expansion',
    description: '+50% resource storage capacity',
    category: 'logistics',
    tier: 2,
    cost: 200,
    timeRequired: 60,
    prerequisites: ['logistics1'],
    effects: [{ type: 'storageBonus', value: 0.5 }],
    emoji: '📦',
  },
];

// --- Worker Definitions ---
export const WORKER_DEFS: Record<string, WorkerDefinition> = {
  engineer: {
    type: 'engineer',
    name: 'Engineer',
    description: 'Boosts factory production speed and efficiency',
    baseHireCost: 500,
    effects: { efficiency: 0.05, speed: 0.08, maintenance: 0.02 },
    emoji: '👷',
  },
  mechanic: {
    type: 'mechanic',
    name: 'Mechanic',
    description: 'Reduces maintenance costs and prevents breakdowns',
    baseHireCost: 400,
    effects: { efficiency: 0.03, speed: 0.05, maintenance: 0.10 },
    emoji: '🔧',
  },
  transportManager: {
    type: 'transportManager',
    name: 'Transport Manager',
    description: 'Optimizes transport routes and increases throughput',
    baseHireCost: 600,
    effects: { efficiency: 0.04, speed: 0.12, maintenance: 0.01 },
    emoji: '📋',
  },
  aiSupervisor: {
    type: 'aiSupervisor',
    name: 'AI Supervisor',
    description: 'Enhances automation systems and AI optimization',
    baseHireCost: 1000,
    effects: { efficiency: 0.08, speed: 0.06, maintenance: 0.03 },
    emoji: '🤖',
  },
};

// --- Market Initial Prices ---
export const INITIAL_MARKET: MarketPrice[] = [
  { resource: 'iron', basePrice: 5, currentPrice: 5, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.1 },
  { resource: 'copper', basePrice: 8, currentPrice: 8, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.12 },
  { resource: 'coal', basePrice: 3, currentPrice: 3, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.08 },
  { resource: 'oil', basePrice: 12, currentPrice: 12, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.15 },
  { resource: 'sand', basePrice: 2, currentPrice: 2, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.06 },
  { resource: 'lithium', basePrice: 20, currentPrice: 20, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.2 },
  { resource: 'water', basePrice: 1, currentPrice: 1, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.05 },
  { resource: 'rareEarth', basePrice: 50, currentPrice: 50, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.25 },
  { resource: 'ironPlate', basePrice: 15, currentPrice: 15, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.1 },
  { resource: 'copperWire', basePrice: 20, currentPrice: 20, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.12 },
  { resource: 'plastic', basePrice: 25, currentPrice: 25, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.13 },
  { resource: 'glass', basePrice: 10, currentPrice: 10, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.08 },
  { resource: 'carbon', basePrice: 18, currentPrice: 18, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.1 },
  { resource: 'gear', basePrice: 40, currentPrice: 40, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.12 },
  { resource: 'circuit', basePrice: 60, currentPrice: 60, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.15 },
  { resource: 'engine', basePrice: 120, currentPrice: 120, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.18 },
  { resource: 'battery', basePrice: 80, currentPrice: 80, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.15 },
  { resource: 'steel', basePrice: 35, currentPrice: 35, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.1 },
  { resource: 'aiChip', basePrice: 300, currentPrice: 300, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.2 },
  { resource: 'robotics', basePrice: 500, currentPrice: 500, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.22 },
  { resource: 'quantumPart', basePrice: 1500, currentPrice: 1500, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.3 },
  { resource: 'advancedAlloy', basePrice: 400, currentPrice: 400, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.18 },
  { resource: 'nanoMaterial', basePrice: 5000, currentPrice: 5000, priceHistory: [], demand: 1, supply: 1, trend: 'stable', volatility: 0.35 },
];

// --- Automation Unlocks ---
export const AUTOMATION_UNLOCKS: AutomationUnlock[] = [
  { type: 'autoRouting', name: 'Auto-Routing', description: 'Automatically optimizes transport routes', cost: 10, active: false, requiresResearch: 'advancedLogistics', emoji: '🔄' },
  { type: 'autoBalancing', name: 'Auto-Balancing', description: 'Balances production across factories', cost: 15, active: false, requiresResearch: 'advancedAutomation', emoji: '⚖️' },
  { type: 'selfRepair', name: 'Self-Repair Bots', description: 'Buildings automatically repair over time', cost: 20, active: false, requiresResearch: 'roboticsTech', emoji: '🛠️' },
  { type: 'autoTrading', name: 'Auto-Trading', description: 'AI trades resources on the market automatically', cost: 25, active: false, requiresResearch: 'marketAnalysis', emoji: '💹' },
  { type: 'autoExpansion', name: 'Auto-Expansion', description: 'AI suggests and builds new production lines', cost: 50, active: false, requiresResearch: 'artificialIntelligence', emoji: '🏗️' },
  { type: 'smartStorage', name: 'Smart Storage', description: 'Automatically distributes resources to where they are needed', cost: 12, active: false, requiresResearch: 'storageExpansion', emoji: '📦' },
  { type: 'aiOptimization', name: 'AI Optimization', description: 'Full AI control over factory optimization', cost: 100, active: false, requiresResearch: 'artificialIntelligence', emoji: '🧠' },
];

// --- Prestige Bonuses ---
export const PRESTIGE_BONUSES: PrestigeBonus[] = [
  { id: 'prodBoost1', name: 'Production Boost I', description: '+25% all production', cost: 5, purchased: false, effect: { type: 'productionMultiplier', value: 0.25 } },
  { id: 'powerBoost1', name: 'Power Boost I', description: '+30% power generation', cost: 5, purchased: false, effect: { type: 'powerMultiplier', value: 0.3 } },
  { id: 'speedBoost1', name: 'Speed Boost I', description: '+20% game speed', cost: 8, purchased: false, effect: { type: 'gameSpeed', value: 0.2 } },
  { id: 'marketBoost1', name: 'Market Boost I', description: '+25% sell prices', cost: 8, purchased: false, effect: { type: 'marketMultiplier', value: 0.25 } },
  { id: 'storageBoost1', name: 'Storage Boost I', description: '+50% storage capacity', cost: 6, purchased: false, effect: { type: 'storageMultiplier', value: 0.5 } },
  { id: 'researchBoost1', name: 'Research Boost I', description: '+30% research speed', cost: 10, purchased: false, effect: { type: 'researchMultiplier', value: 0.3 } },
  { id: 'prodBoost2', name: 'Production Boost II', description: '+50% all production', cost: 15, purchased: false, effect: { type: 'productionMultiplier', value: 0.5 } },
  { id: 'powerBoost2', name: 'Power Boost II', description: '+60% power generation', cost: 15, purchased: false, effect: { type: 'powerMultiplier', value: 0.6 } },
  { id: 'megaFactory', name: 'Mega Factory', description: 'Unlock Mega Factory buildings', cost: 25, purchased: false, effect: { type: 'unlockMegaFactory', value: 1 } },
  { id: 'offProdBoost', name: 'Offline Production', description: '+100% offline production rate', cost: 20, purchased: false, effect: { type: 'offlineMultiplier', value: 1.0 } },
];

// --- Event Templates ---
export const EVENT_TEMPLATES = [
  {
    type: 'oilCrisis' as const,
    name: 'Oil Crisis',
    description: 'Global oil supplies disrupted! Oil prices soar while production slows.',
    duration: 300,
    effects: [
      { type: 'productionMultiplier' as const, target: 'oilPump', value: 0.5 },
      { type: 'marketPriceMultiplier' as const, target: 'oil', value: 2.5 },
    ],
    emoji: '🛢️',
  },
  {
    type: 'energyShortage' as const,
    name: 'Energy Shortage',
    description: 'Power grid under strain! All buildings consume 30% more power.',
    duration: 250,
    effects: [
      { type: 'powerMultiplier' as const, value: 1.3 },
    ],
    emoji: '⚡',
  },
  {
    type: 'aiRevolution' as const,
    name: 'AI Revolution',
    description: 'AI breakthrough! Research speed doubled, AI chip demand surges.',
    duration: 200,
    effects: [
      { type: 'researchSpeed' as const, value: 2.0 },
      { type: 'marketPriceMultiplier' as const, target: 'aiChip', value: 2.0 },
    ],
    emoji: '🧠',
  },
  {
    type: 'economicBoom' as const,
    name: 'Economic Boom',
    description: 'The economy is booming! All sell prices increased by 50%.',
    duration: 300,
    effects: [
      { type: 'marketPriceMultiplier' as const, value: 1.5 },
    ],
    emoji: '📈',
  },
  {
    type: 'naturalDisaster' as const,
    name: 'Natural Disaster',
    description: 'Earthquake damages infrastructure! Production reduced 25%.',
    duration: 150,
    effects: [
      { type: 'productionMultiplier' as const, value: 0.75 },
    ],
    emoji: '🌪️',
  },
  {
    type: 'techBreakthrough' as const,
    name: 'Tech Breakthrough',
    description: 'Scientific breakthrough! All research progresses 50% faster.',
    duration: 250,
    effects: [
      { type: 'researchSpeed' as const, value: 1.5 },
    ],
    emoji: '🔬',
  },
  {
    type: 'tradeWar' as const,
    name: 'Trade War',
    description: 'International tensions rise! Rare earth prices double.',
    duration: 200,
    effects: [
      { type: 'marketPriceMultiplier' as const, target: 'rareEarth', value: 2.0 },
      { type: 'marketPriceMultiplier' as const, target: 'lithium', value: 1.8 },
    ],
    emoji: '⚔️',
  },
  {
    type: 'greenInitiative' as const,
    name: 'Green Initiative',
    description: 'Environmental regulations boost clean energy production!',
    duration: 300,
    effects: [
      { type: 'productionMultiplier' as const, target: 'solarPanel', value: 1.5 },
      { type: 'productionMultiplier' as const, target: 'windTurbine', value: 1.5 },
      { type: 'marketPriceMultiplier' as const, target: 'coal', value: 0.6 },
    ],
    emoji: '🌿',
  },
  {
    type: 'spaceRace' as const,
    name: 'Space Race',
    description: 'Space program demands advanced materials! Quantum and nano prices skyrocket.',
    duration: 250,
    effects: [
      { type: 'marketPriceMultiplier' as const, target: 'quantumPart', value: 3.0 },
      { type: 'marketPriceMultiplier' as const, target: 'nanoMaterial', value: 3.0 },
      { type: 'marketPriceMultiplier' as const, target: 'advancedAlloy', value: 2.0 },
    ],
    emoji: '🚀',
  },
  {
    type: 'marketCrash' as const,
    name: 'Market Crash',
    description: 'Financial crisis! All prices drop 40%.',
    duration: 200,
    effects: [
      { type: 'marketPriceMultiplier' as const, value: 0.6 },
    ],
    emoji: '📉',
  },
];

// --- Tier Info ---
export const TIER_INFO: Record<number, { name: string; emoji: string; color: string; bgColor: string; borderColor: string; description: string }> = {
  0: { name: 'Startup', emoji: '🏗️', color: '#a0a0a0', bgColor: 'rgba(160,160,160,0.08)', borderColor: 'rgba(160,160,160,0.3)', description: 'Raw resources & basic extraction' },
  1: { name: 'Basic Processing', emoji: '🔧', color: '#22d3ee', bgColor: 'rgba(34,211,238,0.08)', borderColor: 'rgba(34,211,238,0.3)', description: 'Smelting, wire drawing, chemical processing' },
  2: { name: 'Advanced Mfg.', emoji: '⚙️', color: '#f97316', bgColor: 'rgba(249,115,22,0.08)', borderColor: 'rgba(249,115,22,0.3)', description: 'Circuits, engines, batteries, gears' },
  3: { name: 'High-Tech', emoji: '🧠', color: '#a855f7', bgColor: 'rgba(168,85,247,0.08)', borderColor: 'rgba(168,85,247,0.3)', description: 'AI, robotics, quantum, nano materials' },
};

// --- Contract Templates (Tier-Based) ---
// Tier 0: Startup (raw resources) | Tier 1: Basic Processing | Tier 2: Advanced Manufacturing | Tier 3: High-Tech/Endgame
export const CONTRACT_TEMPLATES = [
  // === Tier 0: Startup Contracts (raw resources + basic extraction) ===
  { name: 'Iron Ore Delivery', description: 'Deliver iron ore to the steel foundry', type: 'delivery' as const, requiredResources: [{ resource: 'iron' as ResourceType, amount: 100 }], timeLimit: 200, difficulty: 1, gameTier: 0, emoji: '⛏️' },
  { name: 'Coal Supply Run', description: 'Supply coal for the regional power stations', type: 'supply' as const, requiredResources: [{ resource: 'coal' as ResourceType, amount: 80 }], timeLimit: 200, difficulty: 1, gameTier: 0, emoji: '🖤' },
  { name: 'Water Distribution', description: 'Deliver purified water to the industrial zone', type: 'delivery' as const, requiredResources: [{ resource: 'water' as ResourceType, amount: 150 }], timeLimit: 180, difficulty: 1, gameTier: 0, emoji: '💧' },
  { name: 'Copper Shipment', description: 'Ship copper ore to the wire mill', type: 'supply' as const, requiredResources: [{ resource: 'copper' as ResourceType, amount: 60 }], timeLimit: 220, difficulty: 1, gameTier: 0, emoji: '🟤' },
  { name: 'Basic Materials Package', description: 'Deliver a mixed package of iron and coal', type: 'delivery' as const, requiredResources: [{ resource: 'iron' as ResourceType, amount: 50 }, { resource: 'coal' as ResourceType, amount: 30 }], timeLimit: 250, difficulty: 1, gameTier: 0, emoji: '📦' },

  // === Tier 1: Basic Processing Contracts ===
  { name: 'Iron Plate Order', description: 'Deliver iron plates for the construction firm', type: 'delivery' as const, requiredResources: [{ resource: 'ironPlate' as ResourceType, amount: 50 }], timeLimit: 300, difficulty: 2, gameTier: 1, emoji: '🔩' },
  { name: 'Copper Wire Supply', description: 'Supply copper wire for the electronics assembly', type: 'supply' as const, requiredResources: [{ resource: 'copperWire' as ResourceType, amount: 40 }], timeLimit: 280, difficulty: 2, gameTier: 1, emoji: '🔌' },
  { name: 'Glass Delivery', description: 'Deliver glass panes for the commercial district', type: 'delivery' as const, requiredResources: [{ resource: 'glass' as ResourceType, amount: 60 }], timeLimit: 250, difficulty: 2, gameTier: 1, emoji: '🪟' },
  { name: 'Steel Shipment', description: 'Ship steel to the heavy machinery plant', type: 'supply' as const, requiredResources: [{ resource: 'steel' as ResourceType, amount: 50 }], timeLimit: 300, difficulty: 2, gameTier: 1, emoji: '🛡️' },
  { name: 'Plastic Export', description: 'Export plastic for consumer goods manufacturing', type: 'delivery' as const, requiredResources: [{ resource: 'plastic' as ResourceType, amount: 40 }], timeLimit: 280, difficulty: 2, gameTier: 1, emoji: '🧴' },

  // === Tier 2: Advanced Manufacturing Contracts ===
  { name: 'Gear Supply', description: 'Supply precision gears for the manufacturing plant', type: 'supply' as const, requiredResources: [{ resource: 'gear' as ResourceType, amount: 80 }], timeLimit: 300, difficulty: 3, gameTier: 2, emoji: '⚙️' },
  { name: 'Circuit Board Order', description: 'Supply circuits for the electronics plant', type: 'supply' as const, requiredResources: [{ resource: 'circuit' as ResourceType, amount: 30 }], timeLimit: 250, difficulty: 3, gameTier: 2, emoji: '💚' },
  { name: 'Engine Contract', description: 'Deliver engines for military vehicles', type: 'military' as const, requiredResources: [{ resource: 'engine' as ResourceType, amount: 20 }], timeLimit: 400, difficulty: 3, gameTier: 2, emoji: '🔧' },
  { name: 'Battery Shipment', description: 'Ship batteries for the energy storage project', type: 'delivery' as const, requiredResources: [{ resource: 'battery' as ResourceType, amount: 50 }], timeLimit: 350, difficulty: 3, gameTier: 2, emoji: '🔋' },
  { name: 'Electronics Export', description: 'Export consumer electronics abroad', type: 'delivery' as const, requiredResources: [{ resource: 'circuit' as ResourceType, amount: 100 }, { resource: 'plastic' as ResourceType, amount: 50 }], timeLimit: 600, difficulty: 3, gameTier: 2, emoji: '📱' },

  // === Tier 3: High-Tech/Endgame Contracts ===
  { name: 'AI Server Build', description: 'Build AI servers with chips and batteries', type: 'construction' as const, requiredResources: [{ resource: 'aiChip' as ResourceType, amount: 10 }, { resource: 'battery' as ResourceType, amount: 15 }], timeLimit: 500, difficulty: 4, gameTier: 3, emoji: '🖥️' },
  { name: 'Military Robotics', description: 'Fulfill robotics order for the defense contractor', type: 'military' as const, requiredResources: [{ resource: 'robotics' as ResourceType, amount: 8 }, { resource: 'engine' as ResourceType, amount: 10 }], timeLimit: 600, difficulty: 4, gameTier: 3, emoji: '🤖' },
  { name: 'Quantum Research', description: 'Supply quantum parts for the research laboratory', type: 'research' as const, requiredResources: [{ resource: 'quantumPart' as ResourceType, amount: 5 }], timeLimit: 800, difficulty: 5, gameTier: 3, emoji: '⚛️' },
  { name: 'Nano Materials', description: 'Deliver nano materials for a classified project', type: 'military' as const, requiredResources: [{ resource: 'nanoMaterial' as ResourceType, amount: 3 }], timeLimit: 1000, difficulty: 5, gameTier: 3, emoji: '🔮' },
  { name: 'Advanced Alloy Delivery', description: 'Ship advanced alloys for aerospace applications', type: 'delivery' as const, requiredResources: [{ resource: 'advancedAlloy' as ResourceType, amount: 15 }], timeLimit: 700, difficulty: 4, gameTier: 3, emoji: '💠' },
];

// --- Rank Thresholds ---
export const RANK_THRESHOLDS = [
  { name: 'Apprentice', minScore: 0, emoji: '👷', color: '#a0a0a0' },
  { name: 'Foreman', minScore: 100, emoji: '🧑‍🏭', color: '#4ade80' },
  { name: 'Manager', minScore: 500, emoji: '👔', color: '#22d3ee' },
  { name: 'Director', minScore: 2000, emoji: '🎖️', color: '#facc15' },
  { name: 'VP of Operations', minScore: 8000, emoji: '🏅', color: '#fb923c' },
  { name: 'CEO', minScore: 25000, emoji: '👑', color: '#f472b6' },
  { name: 'Tycoon', minScore: 100000, emoji: '💎', color: '#a78bfa' },
  { name: 'Magnate', minScore: 500000, emoji: '🌟', color: '#fbbf24' },
  { name: 'Industrial Legend', minScore: 2000000, emoji: '⚡', color: '#00fff2' },
];

export const PRODUCTION_CHAINS = [
  { name: 'Basic Iron', steps: ['iron', 'ironPlate', 'gear', 'engine'], color: '#a0a0a0' },
  { name: 'Steel Production', steps: ['iron', 'ironPlate', 'steel', 'advancedAlloy'], color: '#708090' },
  { name: 'Electronics', steps: ['copper', 'copperWire', 'circuit', 'aiChip'], color: '#00cc66' },
  { name: 'Energy Storage', steps: ['lithium', 'carbon', 'battery', 'aiChip'], color: '#32cd32' },
  { name: 'Carbon Fiber', steps: ['coal', 'carbon', 'battery'], color: '#2d2d2d' },
  { name: 'Oil Products', steps: ['oil', 'plastic', 'circuit'], color: '#ff6b6b' },
  { name: 'Advanced Materials', steps: ['iron', 'steel', 'advancedAlloy', 'nanoMaterial'], color: '#4169e1' },
  { name: 'Quantum Tech', steps: ['rareEarth', 'aiChip', 'quantumPart', 'nanoMaterial'], color: '#9400d3' },
  { name: 'Robotics', steps: ['gear', 'engine', 'aiChip', 'robotics'], color: '#ff69b4' },
  { name: 'Glass Production', steps: ['sand', 'glass'], color: '#87ceeb' },
];

// --- MegaProject Definitions ---
export const INITIAL_MEGA_PROJECTS: MegaProject[] = [
  {
    type: 'spaceElevator',
    name: 'Space Elevator',
    description: 'Construct a towering tether to orbit, revolutionizing transport capacity across your entire empire.',
    emoji: '🚀',
    stages: [
      {
        name: 'Foundation & Base Tower',
        requiredResources: [
          { resource: 'steel', amount: 1000 },
          { resource: 'gear', amount: 500 },
          { resource: 'circuit', amount: 200 },
        ],
        timeRequired: 500,
        completed: false,
      },
      {
        name: 'Tether & Climber Systems',
        requiredResources: [
          { resource: 'engine', amount: 500 },
          { resource: 'aiChip', amount: 300 },
          { resource: 'robotics', amount: 100 },
        ],
        timeRequired: 1000,
        completed: false,
      },
      {
        name: 'Orbital Station & Activation',
        requiredResources: [
          { resource: 'quantumPart', amount: 50 },
          { resource: 'nanoMaterial', amount: 20 },
          { resource: 'advancedAlloy', amount: 200 },
        ],
        timeRequired: 2000,
        completed: false,
      },
    ],
    currentStage: 0,
    progress: 0,
    active: false,
    completed: false,
    bonus: { type: 'transportMultiplier', description: '+50% transport throughput', value: 0.5 },
    unlockRequirement: { buildings: 20, research: 5 },
  },
  {
    type: 'dysonSphere',
    name: 'Dyson Sphere',
    description: 'Encase a star in a megastructure to harvest unimaginable quantities of energy for your factories.',
    emoji: '☀️',
    stages: [
      {
        name: 'Solar Collector Array',
        requiredResources: [
          { resource: 'steel', amount: 2000 },
          { resource: 'circuit', amount: 1000 },
          { resource: 'battery', amount: 500 },
        ],
        timeRequired: 800,
        completed: false,
      },
      {
        name: 'Energy Transmission Grid',
        requiredResources: [
          { resource: 'aiChip', amount: 1000 },
          { resource: 'robotics', amount: 500 },
          { resource: 'quantumPart', amount: 200 },
        ],
        timeRequired: 1500,
        completed: false,
      },
      {
        name: 'Full Shell Completion',
        requiredResources: [
          { resource: 'nanoMaterial', amount: 100 },
          { resource: 'advancedAlloy', amount: 500 },
          { resource: 'quantumPart', amount: 50 },
        ],
        timeRequired: 3000,
        completed: false,
      },
    ],
    currentStage: 0,
    progress: 0,
    active: false,
    completed: false,
    bonus: { type: 'powerMultiplier', description: '+200% power generation', value: 2.0 },
    unlockRequirement: { buildings: 30, research: 10 },
  },
  {
    type: 'quantumInternet',
    name: 'Quantum Internet',
    description: 'Build an interlocking quantum network that accelerates research beyond the speed of conventional computing.',
    emoji: '🌐',
    stages: [
      {
        name: 'Quantum Node Network',
        requiredResources: [
          { resource: 'circuit', amount: 500 },
          { resource: 'aiChip', amount: 300 },
          { resource: 'battery', amount: 100 },
        ],
        timeRequired: 600,
        completed: false,
      },
      {
        name: 'Entanglement Relays',
        requiredResources: [
          { resource: 'quantumPart', amount: 200 },
          { resource: 'robotics', amount: 100 },
          { resource: 'circuit', amount: 500 },
        ],
        timeRequired: 1200,
        completed: false,
      },
      {
        name: 'Global Quantum Link',
        requiredResources: [
          { resource: 'nanoMaterial', amount: 50 },
          { resource: 'quantumPart', amount: 100 },
          { resource: 'aiChip', amount: 300 },
        ],
        timeRequired: 2000,
        completed: false,
      },
    ],
    currentStage: 0,
    progress: 0,
    active: false,
    completed: false,
    bonus: { type: 'researchMultiplier', description: '+100% research speed', value: 1.0 },
    unlockRequirement: { buildings: 15, research: 8 },
  },
  {
    type: 'fusionCity',
    name: 'Fusion City',
    description: 'Construct a self-sustaining metropolis powered by fusion, doubling all production across your dominion.',
    emoji: '🏙️',
    stages: [
      {
        name: 'City Foundation',
        requiredResources: [
          { resource: 'steel', amount: 3000 },
          { resource: 'gear', amount: 1500 },
          { resource: 'circuit', amount: 800 },
        ],
        timeRequired: 1000,
        completed: false,
      },
      {
        name: 'Fusion Core Installation',
        requiredResources: [
          { resource: 'engine', amount: 1000 },
          { resource: 'battery', amount: 500 },
          { resource: 'aiChip', amount: 300 },
        ],
        timeRequired: 2000,
        completed: false,
      },
      {
        name: 'Infrastructure & Systems',
        requiredResources: [
          { resource: 'robotics', amount: 200 },
          { resource: 'quantumPart', amount: 100 },
          { resource: 'advancedAlloy', amount: 500 },
        ],
        timeRequired: 3000,
        completed: false,
      },
      {
        name: 'City Activation',
        requiredResources: [
          { resource: 'nanoMaterial', amount: 200 },
          { resource: 'quantumPart', amount: 100 },
          { resource: 'aiChip', amount: 1000 },
        ],
        timeRequired: 5000,
        completed: false,
      },
    ],
    currentStage: 0,
    progress: 0,
    active: false,
    completed: false,
    bonus: { type: 'productionMultiplier', description: '+100% all production', value: 1.0 },
    unlockRequirement: { buildings: 40, research: 15, prestige: 2 },
  },
  {
    type: 'terraformingEngine',
    name: 'Terraforming Engine',
    description: 'Reshape entire worlds to your specifications. Removes all resource storage limits forever.',
    emoji: '🌍',
    stages: [
      {
        name: 'Atmospheric Processor',
        requiredResources: [
          { resource: 'steel', amount: 5000 },
          { resource: 'circuit', amount: 2000 },
          { resource: 'battery', amount: 1000 },
        ],
        timeRequired: 1500,
        completed: false,
      },
      {
        name: 'Geothermal Tap Network',
        requiredResources: [
          { resource: 'advancedAlloy', amount: 1000 },
          { resource: 'engine', amount: 500 },
          { resource: 'robotics', amount: 300 },
        ],
        timeRequired: 2500,
        completed: false,
      },
      {
        name: 'Biosphere Seed Vault',
        requiredResources: [
          { resource: 'aiChip', amount: 500 },
          { resource: 'nanoMaterial', amount: 100 },
          { resource: 'quantumPart', amount: 150 },
        ],
        timeRequired: 3500,
        completed: false,
      },
      {
        name: 'Planetary Core Drill',
        requiredResources: [
          { resource: 'nanoMaterial', amount: 200 },
          { resource: 'advancedAlloy', amount: 800 },
          { resource: 'quantumPart', amount: 200 },
        ],
        timeRequired: 4500,
        completed: false,
      },
      {
        name: 'Engine Ignition',
        requiredResources: [
          { resource: 'nanoMaterial', amount: 500 },
          { resource: 'quantumPart', amount: 300 },
          { resource: 'robotics', amount: 500 },
        ],
        timeRequired: 6000,
        completed: false,
      },
    ],
    currentStage: 0,
    progress: 0,
    active: false,
    completed: false,
    bonus: { type: 'unlimitedStorage', description: 'Unlimited resource storage', value: 1 },
    unlockRequirement: { buildings: 50, research: 20, prestige: 3 },
  },
];

// --- Daily Rewards ---
export const WEEKLY_DAILY_REWARDS: Omit<DailyReward, 'claimed'>[] = [
  { day: 1, type: 'money', amount: 500 },
  { day: 2, type: 'researchPoints', amount: 10 },
  { day: 3, type: 'resources', amount: 20, resource: 'iron' },
  { day: 4, type: 'money', amount: 1000 },
  { day: 5, type: 'researchPoints', amount: 30 },
  { day: 6, type: 'resources', amount: 5, resource: 'copperWire' },
  { day: 7, type: 'corporationPoints', amount: 1 }, // JACKPOT day - also gets $2,000 via store logic
];

// Streak multiplier: >=3 days = 1.5x, >=5 days = 2x, >=7 days = 3x
export function getStreakMultiplier(streak: number): number {
  if (streak >= 7) return 3;
  if (streak >= 5) return 2;
  if (streak >= 3) return 1.5;
  return 1;
}

// --- Seasonal Events ---
export const SEASONAL_EVENTS = [
  {
    id: 'doubleProduction',
    name: 'Production Frenzy',
    description: 'All factories produce 2x for a limited time!',
    emoji: '🔥',
    duration: 500,
    effects: [{ type: 'productionMultiplier' as const, value: 2.0 }],
    color: '#ff6600',
    triggerChance: 0.002,
  },
  {
    id: 'researchBoom',
    name: 'Research Boom',
    description: 'Research points accumulate 3x faster!',
    emoji: '🧪',
    duration: 300,
    effects: [{ type: 'researchSpeed' as const, value: 3.0 }],
    color: '#a855f7',
    triggerChance: 0.001,
  },
  {
    id: 'marketSurge',
    name: 'Market Surge',
    description: 'All sell prices increased by 50%!',
    emoji: '📈',
    duration: 400,
    effects: [{ type: 'marketPriceMultiplier' as const, value: 1.5 }],
    color: '#22c55e',
    triggerChance: 0.0015,
  },
  {
    id: 'powerBoost',
    name: 'Power Boost',
    description: 'All power plants produce 2x more energy!',
    emoji: '⚡',
    duration: 600,
    effects: [{ type: 'productionMultiplier' as const, target: 'powerPlant', value: 2.0 }],
    color: '#facc15',
    triggerChance: 0.001,
  },
];

// --- Weather Definitions ---
export const WEATHER_DEFS: Record<WeatherType, WeatherDefinition> = {
  clear: { name: 'Clear Skies', emoji: '☀️', productionMultiplier: 1.0, solarMultiplier: 1.0, windMultiplier: 1.0, description: 'Normal conditions. No weather effects.' },
  sunny: { name: 'Sunny', emoji: '🌞', productionMultiplier: 1.05, solarMultiplier: 1.4, windMultiplier: 0.7, description: 'Bright sunshine! Solar output +40%, wind -30%, production +5%.' },
  rainy: { name: 'Rainy', emoji: '🌧️', productionMultiplier: 0.9, solarMultiplier: 0.3, windMultiplier: 1.2, description: 'Heavy rain reduces solar by 70%. Wind +20%, production -10%.' },
  stormy: { name: 'Stormy', emoji: '⛈️', productionMultiplier: 0.75, solarMultiplier: 0.1, windMultiplier: 1.8, description: 'Dangerous storm! Production -25%, solar -90%, but wind +80%!' },
  foggy: { name: 'Foggy', emoji: '🌫️', productionMultiplier: 0.85, solarMultiplier: 0.5, windMultiplier: 0.6, description: 'Dense fog. Solar -50%, wind -40%, production -15%.' },
  snowy: { name: 'Snowy', emoji: '❄️', productionMultiplier: 0.8, solarMultiplier: 0.4, windMultiplier: 0.8, description: 'Snowfall. Production -20%, solar -60%. Beautiful but cold.' },
};

// --- Quest Definitions ---
export const QUEST_DEFS: Quest[] = [
  // === Tier 0: Startup (guide new players through basics) ===
  {
    id: 'tut_build1',
    name: 'First Steps',
    description: 'Build your first Mining Drill to start producing resources.',
    type: 'build',
    category: 'tutorial',
    gameTier: 0,
    steps: [{ description: 'Build a Mining Drill', target: 1, current: 0, completed: false }],
    reward: { money: 200, researchPoints: 10 },
    completed: false,
    claimed: false,
    emoji: '🏗️',
  },
  {
    id: 'tut_power1',
    name: 'Power Up',
    description: 'Build a Coal Generator to power your factory.',
    type: 'build',
    category: 'tutorial',
    gameTier: 0,
    steps: [{ description: 'Build a Coal Generator', target: 1, current: 0, completed: false }],
    reward: { money: 300, researchPoints: 15 },
    completed: false,
    claimed: false,
    emoji: '⚡',
  },
  {
    id: 'tut_sell1',
    name: 'First Sale',
    description: 'Sell some resources on the market to earn money.',
    type: 'sell',
    category: 'tutorial',
    gameTier: 0,
    steps: [{ description: 'Sell resources on the market', target: 1, current: 0, completed: false }],
    reward: { money: 500, researchPoints: 20 },
    completed: false,
    claimed: false,
    emoji: '💰',
  },
  {
    id: 'tut_extractor2',
    name: 'Expanding Operations',
    description: 'Build 3 extractors and 2 power plants to grow your resource production.',
    type: 'build',
    category: 'tutorial',
    gameTier: 0,
    steps: [
      { description: 'Build extractors (Mining Drill, Oil Pump, etc.)', target: 3, current: 0, completed: false },
      { description: 'Build power plants (Coal Generator, Solar, etc.)', target: 2, current: 0, completed: false },
    ],
    reward: { money: 800, researchPoints: 25 },
    completed: false,
    claimed: false,
    emoji: '⛏️',
  },

  // === Tier 1: Basic Processing (guide players to build T1 factories and research) ===
  {
    id: 't1_factory1',
    name: 'Processing Begins',
    description: 'Build a Smelter to process raw iron into iron plates.',
    type: 'build',
    category: 'tutorial',
    gameTier: 1,
    steps: [{ description: 'Build a Smelter', target: 1, current: 0, completed: false }],
    reward: { money: 800, researchPoints: 25 },
    completed: false,
    claimed: false,
    emoji: '🔥',
  },
  {
    id: 't1_allfactories',
    name: 'Industrial Foundation',
    description: 'Build all basic processing factories: Smelter, Wire Mill, Chemical Plant, Glass Furnace.',
    type: 'build',
    category: 'challenge',
    gameTier: 1,
    steps: [
      { description: 'Build a Smelter', target: 1, current: 0, completed: false },
      { description: 'Build a Wire Mill', target: 1, current: 0, completed: false },
      { description: 'Build a Chemical Plant', target: 1, current: 0, completed: false },
      { description: 'Build a Glass Furnace', target: 1, current: 0, completed: false },
    ],
    reward: { money: 3000, researchPoints: 60 },
    completed: false,
    claimed: false,
    emoji: '🏭',
  },
  {
    id: 't1_research',
    name: 'Knowledge is Power',
    description: 'Start and complete your first research project.',
    type: 'research',
    category: 'tutorial',
    gameTier: 1,
    steps: [{ description: 'Complete a research project', target: 1, current: 0, completed: false }],
    reward: { money: 1000, researchPoints: 50 },
    completed: false,
    claimed: false,
    emoji: '🔬',
  },
  {
    id: 't1_sell_processed',
    name: 'Value Added',
    description: 'Sell processed Tier 1 resources (iron plates, copper wire, etc.) on the market.',
    type: 'sell',
    category: 'daily',
    gameTier: 1,
    steps: [{ description: 'Sell processed resources', target: 5, current: 0, completed: false }],
    reward: { money: 2000, researchPoints: 30 },
    completed: false,
    claimed: false,
    emoji: '🔩',
  },

  // === Tier 2: Advanced Manufacturing (T2 factories, research chains, workers) ===
  {
    id: 't2_gearfactory',
    name: 'Precision Engineering',
    description: 'Research Basic Machining and build a Gear Factory.',
    type: 'build',
    category: 'challenge',
    gameTier: 2,
    steps: [
      { description: 'Research Basic Machining', target: 1, current: 0, completed: false },
      { description: 'Build a Gear Factory', target: 1, current: 0, completed: false },
    ],
    reward: { money: 5000, researchPoints: 80 },
    completed: false,
    claimed: false,
    emoji: '⚙️',
  },
  {
    id: 't2_circuitfactory',
    name: 'Silicon Valley',
    description: 'Research Electronics and build a Circuit Factory.',
    type: 'build',
    category: 'challenge',
    gameTier: 2,
    steps: [
      { description: 'Research Electronics', target: 1, current: 0, completed: false },
      { description: 'Build a Circuit Factory', target: 1, current: 0, completed: false },
    ],
    reward: { money: 6000, researchPoints: 100 },
    completed: false,
    claimed: false,
    emoji: '💚',
  },
  {
    id: 't2_hire_workers',
    name: 'Workforce',
    description: 'Hire workers to boost your factory efficiency.',
    type: 'build',
    category: 'challenge',
    gameTier: 2,
    steps: [{ description: 'Hire workers', target: 3, current: 0, completed: false }],
    reward: { money: 3000, researchPoints: 50 },
    completed: false,
    claimed: false,
    emoji: '👷',
  },
  {
    id: 't2_nuclear',
    name: 'Nuclear Age',
    description: 'Research Nuclear Power and build a Nuclear Reactor for massive energy.',
    type: 'build',
    category: 'challenge',
    gameTier: 2,
    steps: [
      { description: 'Research Nuclear Power', target: 1, current: 0, completed: false },
      { description: 'Build a Nuclear Reactor', target: 1, current: 0, completed: false },
    ],
    reward: { money: 8000, researchPoints: 120 },
    completed: false,
    claimed: false,
    emoji: '☢️',
  },

  // === Tier 3: Endgame (T3 factories, mega projects, high efficiency) ===
  {
    id: 't3_ailab',
    name: 'Artificial Minds',
    description: 'Research Artificial Intelligence and build an AI Lab.',
    type: 'build',
    category: 'challenge',
    gameTier: 3,
    steps: [
      { description: 'Research Artificial Intelligence', target: 1, current: 0, completed: false },
      { description: 'Build an AI Lab', target: 1, current: 0, completed: false },
    ],
    reward: { money: 15000, researchPoints: 200 },
    completed: false,
    claimed: false,
    emoji: '🧠',
  },
  {
    id: 't3_megaproject',
    name: 'Mega Aspirations',
    description: 'Start a Mega Project and make progress toward completion.',
    type: 'build',
    category: 'challenge',
    gameTier: 3,
    steps: [
      { description: 'Start a Mega Project', target: 1, current: 0, completed: false },
      { description: 'Reach 20% progress on any Mega Project', target: 20, current: 0, completed: false },
    ],
    reward: { money: 25000, researchPoints: 300, corporationPoints: 5 },
    completed: false,
    claimed: false,
    emoji: '🚀',
  },
  {
    id: 't3_efficiency',
    name: 'Peak Performance',
    description: 'Achieve 90%+ power efficiency across your factory.',
    type: 'reach',
    category: 'challenge',
    gameTier: 3,
    steps: [{ description: 'Reach 90% power efficiency', target: 90, current: 0, completed: false }],
    reward: { money: 10000, researchPoints: 150, corporationPoints: 3 },
    completed: false,
    claimed: false,
    emoji: '⚡',
  },
  {
    id: 't3_quantum',
    name: 'Quantum Leap',
    description: 'Research Quantum Physics and build a Quantum Lab.',
    type: 'build',
    category: 'challenge',
    gameTier: 3,
    steps: [
      { description: 'Research Quantum Physics', target: 1, current: 0, completed: false },
      { description: 'Build a Quantum Lab', target: 1, current: 0, completed: false },
    ],
    reward: { money: 20000, researchPoints: 250 },
    completed: false,
    claimed: false,
    emoji: '⚛️',
  },

  // Daily quests (recurring, scale with player tier)
  {
    id: 'daily_build',
    name: 'Daily Builder',
    description: 'Build 3 new buildings today.',
    type: 'build',
    category: 'daily',
    gameTier: 0,
    steps: [{ description: 'Build new buildings', target: 3, current: 0, completed: false }],
    reward: { money: 2000, researchPoints: 30 },
    completed: false,
    claimed: false,
    emoji: '🏗️',
  },
  {
    id: 'daily_earn',
    name: 'Daily Earnings',
    description: 'Earn $5,000 from sales today.',
    type: 'earn',
    category: 'daily',
    gameTier: 0,
    steps: [{ description: 'Earn money from sales', target: 5000, current: 0, completed: false }],
    reward: { money: 3000, researchPoints: 40 },
    completed: false,
    claimed: false,
    emoji: '💵',
  },
  // Prestige challenge
  {
    id: 'challenge_prestige',
    name: 'Global Expansion',
    description: 'Prestige to expand your corporation globally and unlock permanent bonuses.',
    type: 'reach',
    category: 'challenge',
    gameTier: 3,
    steps: [{ description: 'Prestige (Global Expansion)', target: 1, current: 0, completed: false }],
    reward: { money: 50000, researchPoints: 500, corporationPoints: 10 },
    completed: false,
    claimed: false,
    emoji: '🌍',
  },
];
