// ============================================
// IndustryaX: UI Catalog — Buildings + Mega Projects
// Static presentation metadata only (no game-logic Master fields).
// Split from uiCatalog.ts — behavior-identical data move.
// ============================================

import type { BuildingType } from '../../shared/types/types';

export type BuildingUIMeta = {
  type: BuildingType;
  name: string;
  description: string;
  category: 'extractor' | 'factory' | 'power' | 'storage';
  tier: number;
  icon: string;
};

export const BUILDING_UI: Record<string, BuildingUIMeta> = {
  ironMine: {
    "type": "ironMine",
    "name": "Iron Mine",
    "description": "Extracts iron ore from mineral deposits",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:mine-wagon",
  },
  oilPump: {
    "type": "oilPump",
    "name": "Oil Pump",
    "description": "Pumps crude oil from underground reserves",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:oil-rig",
  },
  waterExtractor: {
    "type": "waterExtractor",
    "name": "Water Extractor",
    "description": "Extracts and purifies water from the environment",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:water-recycling",
  },
  sandMine: {
    "type": "sandMine",
    "name": "Sand Mine",
    "description": "Extracts sand for glass and silicon production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:desert",
  },
  clayPit: {
    "type": "clayPit",
    "name": "Clay Pit",
    "description": "Extracts clay for brick and concrete production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:clay-brick",
  },
  limestoneQuarry: {
    "type": "limestoneQuarry",
    "name": "Limestone Quarry",
    "description": "Quarries limestone for construction and chemistry",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:stone-bridge",
  },
  gravelPit: {
    "type": "gravelPit",
    "name": "Gravel Pit",
    "description": "Extracts gravel for concrete production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:stone-crafting",
  },
  bauxiteMine: {
    "type": "bauxiteMine",
    "name": "Bauxite Mine",
    "description": "Mines bauxite ore for aluminium production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:mining-helmet",
  },
  wolframiteMine: {
    "type": "wolframiteMine",
    "name": "Wolframite Mine",
    "description": "Mines wolframite for tungsten extraction",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:obelisk",
  },
  rareEarthExtractor: {
    "type": "rareEarthExtractor",
    "name": "Rare Earth Extractor",
    "description": "Specialized extraction facility that processes mineral deposits for rare earth elements",
    "category": "extractor",
    "tier": 1,
    "icon": "game-icons:crystal-shine",
  },
  copperMine: {
    "type": "copperMine",
    "name": "Copper Mine",
    "description": "Extracts copper ore from mineral veins",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:ore",
  },
  coalMine: {
    "type": "coalMine",
    "name": "Coal Mine",
    "description": "Mines coal from underground seams for fuel and carbon processing",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:coal-wagon",
  },
  lithiumMine: {
    "type": "lithiumMine",
    "name": "Lithium Mine",
    "description": "Mines lithium deposits for battery and advanced tech production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:crystal-cluster",
  },
  silverMine: {
    "type": "silverMine",
    "name": "Silver Mine",
    "description": "Extracts silver ore from mineral veins",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:shield-impact",
  },
  goldMine: {
    "type": "goldMine",
    "name": "Gold Mine",
    "description": "Mines gold deposits for luxury and economic production",
    "category": "extractor",
    "tier": 0,
    "icon": "game-icons:gold-bar",
  },
  smelter: {
    "type": "smelter",
    "name": "Smelter",
    "description": "Smelts iron ore into iron plates for manufacturing",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:furnace",
  },
  wireMill: {
    "type": "wireMill",
    "name": "Wire Mill",
    "description": "Draws copper ore into fine copper wire",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:wire-coil",
  },
  chemicalPlant: {
    "type": "chemicalPlant",
    "name": "Chemical Plant",
    "description": "Processes oil into plastic and coal into carbon fiber",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:chemical-drop",
  },
  glassFurnace: {
    "type": "glassFurnace",
    "name": "Glass Furnace",
    "description": "Melts sand into glass panes",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:glass-celebration",
  },
  steelForge: {
    "type": "steelForge",
    "name": "Steel Forge",
    "description": "Forges iron and coal into strong steel alloys",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:anvil-impact",
  },
  carbonProcessor: {
    "type": "carbonProcessor",
    "name": "Carbon Processor",
    "description": "Processes coal into high-grade carbon fiber for advanced manufacturing",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:coal-pile",
  },
  brickFactory: {
    "type": "brickFactory",
    "name": "Brick Factory",
    "description": "Bakes clay into sturdy bricks",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:brick-wall",
  },
  concreteFactory: {
    "type": "concreteFactory",
    "name": "Concrete Factory",
    "description": "Mixes gravel and limestone into concrete",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:concrete-bag",
  },
  fertilizerFactory: {
    "type": "fertilizerFactory",
    "name": "Fertilizer Factory",
    "description": "Produces fertilizer from limestone",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:seedling",
  },
  oilRefinery: {
    "type": "oilRefinery",
    "name": "Oil Refinery",
    "description": "Refines crude oil into fossil fuel",
    "category": "factory",
    "tier": 1,
    "icon": "game-icons:refinery",
  },
  gearFactory: {
    "type": "gearFactory",
    "name": "Gear Factory",
    "description": "Manufactures precision gears from iron plates",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:big-gear",
  },
  circuitFactory: {
    "type": "circuitFactory",
    "name": "Circuit Factory",
    "description": "Assembles circuit boards from copper wire and plastic",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:circuitry",
  },
  engineFactory: {
    "type": "engineFactory",
    "name": "Engine Factory",
    "description": "Builds powerful engines from gears and steel",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:gear-stick",
  },
  batteryFactory: {
    "type": "batteryFactory",
    "name": "Battery Factory",
    "description": "Produces batteries from lithium and carbon fiber",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:battery-75",
  },
  siliconRefinery: {
    "type": "siliconRefinery",
    "name": "Silicon Refinery",
    "description": "Refines quartz sand and clay into silicon wafers",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:processor",
  },
  aluminiumFactory: {
    "type": "aluminiumFactory",
    "name": "Aluminium Factory",
    "description": "Smelts bauxite into lightweight aluminium",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:metal-disc",
  },
  insecticideFactory: {
    "type": "insecticideFactory",
    "name": "Insecticide Factory",
    "description": "Produces insecticides from copper and limestone",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:poison",
  },
  copperRefinery: {
    "type": "copperRefinery",
    "name": "Copper Refinery",
    "description": "Refines raw copper ore into pure copper ingots",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:metal-scales",
  },
  titaniumRefinery: {
    "type": "titaniumRefinery",
    "name": "Titanium Refinery",
    "description": "Processes rare earth elements to extract titanium compounds",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:shield-impact",
  },
  coolantPlant: {
    "type": "coolantPlant",
    "name": "Coolant Plant",
    "description": "Processes water and oil into industrial coolant",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:snowflake-2",
  },
  opticsLab: {
    "type": "opticsLab",
    "name": "Optics Lab",
    "description": "Manufactures fiber optics from glass and copper wire",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:laser-burst",
  },
  solarCellFactory: {
    "type": "solarCellFactory",
    "name": "Solar Cell Factory",
    "description": "Produces solar cells from glass and silicon",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:solar-power",
  },
  displayFactory: {
    "type": "displayFactory",
    "name": "Electro-Optics Plant",
    "description": "Manufactures fiber optics and circuit boards from glass, copper wire, and plastic — a versatile optoelectronics facility",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:tv",
  },
  hydrogenPlant: {
    "type": "hydrogenPlant",
    "name": "Hydrogen Fuel Plant",
    "description": "Extracts hydrogen from water through electrolysis to produce synthetic fossil fuel with coolant as byproduct",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:h2o",
  },
  reinforcedConcretePlant: {
    "type": "reinforcedConcretePlant",
    "name": "Reinforced Concrete Plant",
    "description": "Reinforces concrete with steel for mega construction",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:concrete-bag",
  },
  powerCellPlant: {
    "type": "powerCellPlant",
    "name": "Power Cell Plant",
    "description": "Manufactures power cells from batteries and fossil fuel — the backbone of the energy tier system",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:battery-100",
  },
  silverRefinery: {
    "type": "silverRefinery",
    "name": "Silver Refinery",
    "description": "Refines raw silver into high-purity refined silver for jewellery and electronics",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:shield-impact",
  },
  goldRefinery: {
    "type": "goldRefinery",
    "name": "Gold Refinery",
    "description": "Refines raw gold into pure refined gold for luxury production",
    "category": "factory",
    "tier": 2,
    "icon": "game-icons:gold-bar",
  },
  aiLab: {
    "type": "aiLab",
    "name": "AI Lab",
    "description": "Creates advanced AI chips from circuits and batteries",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:brain",
  },
  roboticsBay: {
    "type": "roboticsBay",
    "name": "Robotics Bay",
    "description": "Assembles robotic units from AI chips and engines",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:robot-grab",
  },
  quantumLab: {
    "type": "quantumLab",
    "name": "Quantum Lab",
    "description": "Produces quantum components using AI chips and rare earth",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:atom",
  },
  alloyForge: {
    "type": "alloyForge",
    "name": "Alloy Forge",
    "description": "Forges advanced alloys from steel and lithium",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:metal-bar",
  },
  nanoLab: {
    "type": "nanoLab",
    "name": "Nano Lab",
    "description": "Synthesizes nano materials from advanced alloys and quantum parts",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:nano-bot",
  },
  electronicsFactory: {
    "type": "electronicsFactory",
    "name": "Electronics Factory",
    "description": "Assembles advanced electronics from circuits, plastics, and silicon",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:smartphone",
  },
  medicalTechLab: {
    "type": "medicalTechLab",
    "name": "Medical Tech Lab",
    "description": "Produces medical technology from titanium, plastics, and electronics",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:hospital-cross",
  },
  jewelleryForge: {
    "type": "jewelleryForge",
    "name": "Jewellery Forge",
    "description": "Forges precious jewellery from refined gold, silver, and rare earth elements",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:diamond-ring",
  },
  tungstenSmelter: {
    "type": "tungstenSmelter",
    "name": "Tungsten Smelter",
    "description": "Smelts wolframite into tough tungsten with fossil fuel and limestone",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:iron-cross",
  },
  armsFactory: {
    "type": "armsFactory",
    "name": "Arms Factory",
    "description": "Manufactures weapons from steel, aluminium, and batteries",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:ak47",
  },
  droneShipyard: {
    "type": "droneShipyard",
    "name": "Drone Shipyard",
    "description": "Builds scan drones from electronics, titanium, and batteries",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:space-shuttle",
  },
  detectorFactory: {
    "type": "detectorFactory",
    "name": "Detector Factory",
    "description": "Builds artifact detectors from batteries, electronics, and tungsten",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:satellite",
  },
  neuralLab: {
    "type": "neuralLab",
    "name": "Neural Lab",
    "description": "Constructs neural networks from fiber optics and AI chips",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:thought-bubble",
  },
  quantumAssembler: {
    "type": "quantumAssembler",
    "name": "Quantum Assembler",
    "description": "Alternative quantum part producer — assembles quantum components from AI chips, rare earth, and fibre optics without requiring deep artifact detector chains",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:atom",
  },
  opticalComputingLab: {
    "type": "opticalComputingLab",
    "name": "Optical Computing Lab",
    "description": "Alternative AI Chip production using fiber optics and silicon — bypasses the copper bottleneck",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:laser-burst",
  },
  carbonCompositePlant: {
    "type": "carbonCompositePlant",
    "name": "Carbon Composite Plant",
    "description": "Combines carbon fiber with advanced alloys for ultra-strong composite materials",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:rope-coil",
  },
  structuralFrameFactory: {
    "type": "structuralFrameFactory",
    "name": "Structural Frame Factory",
    "description": "Assembles structural frames from steel and reinforced concrete for mega construction",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:bridge",
  },
  fusionReactor: {
    "type": "fusionReactor",
    "name": "Fusion Reactor",
    "description": "Generates fusion cells — an alternative high-tier energy source using lithium and power cells",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:nuclear-bomb",
  },
  solarPanelFactory: {
    "type": "solarPanelFactory",
    "name": "Solar Panel Factory",
    "description": "Assembles solar panels from solar cells, circuits, and aluminium — feeds the Dyson Collector",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:solar-power",
  },
  creditMint: {
    "type": "creditMint",
    "name": "Credit Mint",
    "description": "Mints credit chips from jewellery and advanced electronics — the foundation of the economy lane",
    "category": "factory",
    "tier": 3,
    "icon": "game-icons:credit-card",
  },
  singularityForge: {
    "type": "singularityForge",
    "name": "Singularity Forge",
    "description": "Forges singularity cores from quantum parts, nano materials, and AI chips",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:vortex",
  },
  darkMatterLab: {
    "type": "darkMatterLab",
    "name": "Dark Matter Lab",
    "description": "Synthesizes dark matter cells from nano materials and advanced alloys under extreme coolant conditions",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:hole",
  },
  warpDriveFactory: {
    "type": "warpDriveFactory",
    "name": "Warp Drive Factory",
    "description": "Constructs FTL warp drives from engines, robotics, and quantum parts",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:rocket-thruster",
  },
  antimatterReactor: {
    "type": "antimatterReactor",
    "name": "Antimatter Reactor",
    "description": "Produces antimatter fuel from advanced electronics, quantum components, and coolant under controlled conditions",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:lightning-frequency",
  },
  chronoLab: {
    "type": "chronoLab",
    "name": "Chrono Lab",
    "description": "Manufactures temporal components from singularity cores and neural networks",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:hourglass",
  },
  plasmaForge: {
    "type": "plasmaForge",
    "name": "Plasma Forge",
    "description": "Creates plasma cores from advanced alloys, fossil fuel, and coolant at extreme temperatures",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:flame-tunnel",
  },
  megaStructureFactory: {
    "type": "megaStructureFactory",
    "name": "Mega Structure Factory",
    "description": "Assembles massive construction modules from reinforced concrete, steel, advanced alloys, and robotics",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:castle",
  },
  voidCrystallizer: {
    "type": "voidCrystallizer",
    "name": "Void Crystallizer",
    "description": "Crystallizes void energy from rare earth, nano materials, and quantum parts",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:implosion",
  },
  quantumResonanceLab: {
    "type": "quantumResonanceLab",
    "name": "Quantum Resonance Lab",
    "description": "Alternative quantum part production using plasma energy — bypasses the artifact detector bottleneck",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:atom",
  },
  arcologyBuilder: {
    "type": "arcologyBuilder",
    "name": "Arcology Builder",
    "description": "Constructs arcology modules — self-contained mega-habitats for millions",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:modern-city",
  },
  habitatModuleFactory: {
    "type": "habitatModuleFactory",
    "name": "Habitat Module Factory",
    "description": "Manufactures habitat modules from carbon composites and advanced alloys for orbital construction",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:house",
  },
  luxuryGoodsFactory: {
    "type": "luxuryGoodsFactory",
    "name": "Luxury Goods Factory",
    "description": "Produces luxury goods from jewellery, carbon composites, and solar panels for the premium market",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:diamond-ring",
  },
  tradeHub: {
    "type": "tradeHub",
    "name": "Trade Hub",
    "description": "Processes credit chips, luxury goods, and fiber optics into trade contracts",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:hand",
  },
  teleporterGate: {
    "type": "teleporterGate",
    "name": "Teleporter Gate",
    "description": "Constructs teleporter nodes using quantum parts and fiber optics — enables instant resource transport",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:teleport",
  },
  dysonCollector: {
    "type": "dysonCollector",
    "name": "Dyson Collector",
    "description": "Harvests stellar energy using solar panels and structural frames — produces stellar energy",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:solar-system",
  },
  quantumTeleporter: {
    "type": "quantumTeleporter",
    "name": "Quantum Teleporter",
    "description": "Generates research points through quantum entanglement — requires continuous inputs",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:teleport",
  },
  dimensionalGateway: {
    "type": "dimensionalGateway",
    "name": "Dimensional Gateway",
    "description": "Opens portals to other dimensions using void crystals and dark matter — generates corporation points",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:portal",
  },
  timeDistorter: {
    "type": "timeDistorter",
    "name": "Time Distorter",
    "description": "Bends time using chrono parts and plasma — generates money and research points",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:hourglass",
  },
  galacticForge: {
    "type": "galacticForge",
    "name": "Galactic Forge",
    "description": "The ultimate factory — combines singularity, warp, and void technology for immense output",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:castle",
  },
  omniscienceArray: {
    "type": "omniscienceArray",
    "name": "Omniscience Array",
    "description": "The pinnacle of tech ascension — produces research matrices for total knowledge domination",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:brain",
  },
  worldEngine: {
    "type": "worldEngine",
    "name": "World Engine",
    "description": "Planetary-scale construction engine — builds world cores from arcology modules and stellar energy",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:planet-core",
  },
  planetaryShield: {
    "type": "planetaryShield",
    "name": "Planetary Shield",
    "description": "Constructs a shield matrix — the ultimate defense and production multiplier for your entire empire",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:shield-impact",
  },
  starReactor: {
    "type": "starReactor",
    "name": "Star Reactor",
    "description": "Harnesses antimatter and fusion to create stellar forges — the peak of energy mastery",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:star-formation",
  },
  voidEngine: {
    "type": "voidEngine",
    "name": "Void Engine",
    "description": "Generates void energy from dark matter and quantum parts — the ultimate power source that fuels all T5 systems",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:hole",
  },
  quantumExchange: {
    "type": "quantumExchange",
    "name": "Quantum Exchange",
    "description": "Quantum-powered trading platform — creates market dominance from trade contracts and singularity cores",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:chart",
  },
  megaCorpHQ: {
    "type": "megaCorpHQ",
    "name": "Mega Corp HQ",
    "description": "The ultimate corporate headquarters — generates massive wealth using world cores and stellar forges",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:bank",
  },
  dimensionalNexus: {
    "type": "dimensionalNexus",
    "name": "Dimensional Nexus",
    "description": "Opens dimensional gates using teleporter nodes and void energy — enables exploration of new realities",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:portal",
  },
  galacticArmada: {
    "type": "galacticArmada",
    "name": "Galactic Armada",
    "description": "Builds the ultimate fleet from warp drives, robotics, and stellar forges — dominates the galaxy",
    "category": "factory",
    "tier": 5,
    "icon": "game-icons:spaceship",
  },
  coalGenerator: {
    "type": "coalGenerator",
    "name": "Coal Generator",
    "description": "Burns coal to generate electricity. Reliable but dirty.",
    "category": "power",
    "tier": 0,
    "icon": "game-icons:refinery",
  },
  solarFarm: {
    "type": "solarFarm",
    "name": "Solar Farm",
    "description": "Clean energy from the sun. Low output but free fuel.",
    "category": "power",
    "tier": 0,
    "icon": "game-icons:solar-power",
  },
  windTurbine: {
    "type": "windTurbine",
    "name": "Wind Turbine",
    "description": "Harnesses wind power. Variable output.",
    "category": "power",
    "tier": 0,
    "icon": "game-icons:wind-turbine",
  },
  nuclearReactor: {
    "type": "nuclearReactor",
    "name": "Nuclear Reactor",
    "description": "Massive power output. Expensive to build.",
    "category": "power",
    "tier": 2,
    "icon": "game-icons:nuclear",
  },
  antimatterPowerPlant: {
    "type": "antimatterPowerPlant",
    "name": "Antimatter Power Plant",
    "description": "Generates enormous power from antimatter annihilation. The ultimate energy source.",
    "category": "power",
    "tier": 4,
    "icon": "game-icons:lightning-frequency",
  },
  // ─── Tier-4.5 endgame resource producers (Phase B of TIER5_WIRING_PLAN) ───
  arcologyModuleAssembler: {
    "type": "arcologyModuleAssembler",
    "name": "Arcology Module Assembler",
    "description": "Assembles advanced arcology modules from structural components",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:city",
  },
  stellarForgeModule: {
    "type": "stellarForgeModule",
    "name": "Stellar Forge Module",
    "description": "Forges stellar components from fusion energy and mega structures",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:star-swirl",
  },
  voidEnergyCollector: {
    "type": "voidEnergyCollector",
    "name": "Void Energy Collector",
    "description": "Harvests void energy from antimatter and quantum fluctuations",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:void",
  },
  tradeContractBroker: {
    "type": "tradeContractBroker",
    "name": "Trade Contract Broker",
    "description": "Brokerage that converts luxury goods into binding trade contracts",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:scroll-quill",
  },
  marketDominanceCenter: {
    "type": "marketDominanceCenter",
    "name": "Market Dominance Center",
    "description": "Establishes market dominance through credit chips and trade contracts",
    "category": "factory",
    "tier": 4,
    "icon": "game-icons:crown",
  },
} as Record<string, BuildingUIMeta>;

export type MegaProjectUIMeta = {
  type: string;
  name: string;
  description: string;
  icon: string;
};

export const MEGA_PROJECT_UI: MegaProjectUIMeta[] = [
  {
    "type": "spaceElevator",
    "name": "Space Elevator",
    "description": "Construct a towering tether to orbit, revolutionizing transport capacity across your entire empire.",
    "icon": "game-icons:rocket-thruster",
  },
  {
    "type": "dysonSphere",
    "name": "Dyson Sphere",
    "description": "Encase a star in a megastructure to harvest unimaginable quantities of energy for your factories.",
    "icon": "game-icons:solar-system",
  },
  {
    "type": "quantumInternet",
    "name": "Quantum Internet",
    "description": "Build an interlocking quantum network that accelerates research beyond the speed of conventional computing.",
    "icon": "game-icons:spider-web",
  },
  {
    "type": "fusionCity",
    "name": "Fusion City",
    "description": "Construct a self-sustaining metropolis powered by fusion, doubling all production across your dominion.",
    "icon": "game-icons:bank",
  },
  {
    "type": "terraformingEngine",
    "name": "Terraforming Engine",
    "description": "Reshape entire worlds to your specifications. Removes all resource storage limits forever.",
    "icon": "game-icons:crystal-growth",
  },
  {
    "type": "galacticTradeHub",
    "name": "Galactic Trade Hub",
    "description": "Construct an interstellar commerce nexus that commands premium prices across all galactic markets.",
    "icon": "game-icons:shop",
  },
  {
    "type": "deepCoreExtractor",
    "name": "Deep Core Extractor",
    "description": "Bore into the planet's mantle with a mega-drill that dramatically accelerates all raw material extraction.",
    "icon": "game-icons:mining",
  },
  {
    "type": "neuralCommandCenter",
    "name": "Neural Command Center",
    "description": "Deploy a planet-wide neural network that synchronizes and supercharges every worker in your empire.",
    "icon": "game-icons:brain",
  },
  {
    "type": "nanoAssemblyMatrix",
    "name": "Nano Assembly Matrix",
    "description": "Build a molecular-scale fabrication swarm that slashes construction costs across your entire dominion.",
    "icon": "game-icons:nano-bot",
  }
];

