// ============================================
// IndustryaX: UI Catalog — Quests
// Static presentation metadata only (no game-logic Master fields).
// Split from uiCatalog.ts — behavior-identical data move.
// ============================================

export type QuestUIMeta = {
  id: string;
  name: string;
  description: string;
  icon: string;
};

export const QUEST_UI: QuestUIMeta[] = [
  {
    "id": "tut_build1",
    "name": "First Steps",
    "description": "Build your first Iron Mine to start producing resources.",
    "icon": "game-icons:mine-wagon",
  },
  {
    "id": "tut_power1",
    "name": "Power Up",
    "description": "Build a Coal Generator to power your factory.",
    "icon": "game-icons:factory",
  },
  {
    "id": "tut_sell1",
    "name": "First Sale",
    "description": "Sell some resources on the market to earn money.",
    "icon": "game-icons:coins",
  },
  {
    "id": "tut_extractor2",
    "name": "Expanding Operations",
    "description": "Build 3 extractors and 2 power plants to grow your resource production.",
    "icon": "game-icons:mining",
  },
  {
    "id": "tut_oil_water",
    "name": "Diversify Resources",
    "description": "Build an Oil Pump and Water Extractor to access more raw materials.",
    "icon": "game-icons:oil-rig",
  },
  {
    "id": "tut_transport1",
    "name": "Logistics Begin",
    "description": "Build your first transport line to connect a producer to a consumer.",
    "icon": "game-icons:tread",
  },
  {
    "id": "t1_smelter",
    "name": "Processing Begins",
    "description": "Build a Smelter to process raw iron into iron plates.",
    "icon": "game-icons:furnace",
  },
  {
    "id": "t1_allfactories",
    "name": "Industrial Foundation",
    "description": "Build all basic processing factories: Smelter, Wire Mill, Chemical Plant, Glass Furnace.",
    "icon": "game-icons:factory",
  },
  {
    "id": "t1_research",
    "name": "Knowledge is Power",
    "description": "Start and complete your first research project.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "t1_steel_forge",
    "name": "Steel Strong",
    "description": "Build a Steel Forge to create advanced steel alloys from iron and coal.",
    "icon": "game-icons:anvil-impact",
  },
  {
    "id": "t1_construction",
    "name": "Construction Empire",
    "description": "Build Brick Factory and Concrete Factory for construction materials.",
    "icon": "game-icons:castle",
  },
  {
    "id": "t1_produce_ironplate",
    "name": "Iron Plate Milestone",
    "description": "Produce 50 iron plates in your smelters.",
    "icon": "game-icons:metal-plate",
  },
  {
    "id": "t1_sell_processed",
    "name": "Value Added",
    "description": "Sell processed Tier 1 resources on the market.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t1_contract_first",
    "name": "Contractor",
    "description": "Complete your first contract to build business relationships.",
    "icon": "game-icons:scroll-unfurled",
  },
  {
    "id": "t1_carbon",
    "name": "Carbon Fiber Pioneer",
    "description": "Build a Carbon Processor to convert coal into high-grade carbon fiber.",
    "icon": "game-icons:coal-pile",
  },
  {
    "id": "t1_oil_refinery",
    "name": "Fuel Refinement",
    "description": "Build an Oil Refinery to process crude oil into fossil fuel.",
    "icon": "game-icons:refinery",
  },
  {
    "id": "t1_fertilizer",
    "name": "Green Revolution",
    "description": "Build a Fertilizer Factory to produce fertilizer from limestone and water.",
    "icon": "game-icons:fertilizer-bag",
  },
  {
    "id": "t1_produce_copperwire",
    "name": "Copper Wire Milestone",
    "description": "Produce 50 copper wires in your wire mill.",
    "icon": "game-icons:electric",
  },
  {
    "id": "t1_produce_plastic",
    "name": "Plastic Milestone",
    "description": "Produce 30 plastic in your chemical plant.",
    "icon": "game-icons:plastic-duck",
  },
  {
    "id": "t1_produce_glass",
    "name": "Glass Milestone",
    "description": "Produce 40 glass in your glass furnace.",
    "icon": "game-icons:glass-celebration",
  },
  {
    "id": "t1_produce_steel",
    "name": "Steel Milestone",
    "description": "Produce 25 steel in your steel forge.",
    "icon": "game-icons:steel-claws",
  },
  {
    "id": "t1_produce_bricks",
    "name": "Bricks Milestone",
    "description": "Produce 50 bricks in your brick factory.",
    "icon": "game-icons:brick-wall",
  },
  {
    "id": "t1_produce_concrete",
    "name": "Concrete Milestone",
    "description": "Produce 20 concrete in your concrete factory.",
    "icon": "game-icons:concrete-bag",
  },
  {
    "id": "t1_produce_carbon",
    "name": "Carbon Fiber Milestone",
    "description": "Produce 20 carbon fiber in your carbon processor.",
    "icon": "game-icons:coal-pile",
  },
  {
    "id": "t1_produce_fossilfuel",
    "name": "Fossil Fuel Milestone",
    "description": "Produce 30 fossil fuel in your oil refinery.",
    "icon": "game-icons:fuel-tank",
  },
  {
    "id": "t1_daily_raw_sell",
    "name": "Raw Material Trader",
    "description": "Sell raw resources (iron, copper, coal, oil) on the market.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t1_daily_t1_sell",
    "name": "Processed Goods Trader",
    "description": "Sell Tier 1 processed resources (iron plates, copper wire, etc.) on the market.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t2_gearfactory",
    "name": "Precision Engineering",
    "description": "Research Basic Machining and build a Gear Factory.",
    "icon": "game-icons:big-gear",
  },
  {
    "id": "t2_circuitfactory",
    "name": "Silicon Valley",
    "description": "Research Electronics and build a Circuit Factory.",
    "icon": "game-icons:circuitry",
  },
  {
    "id": "t2_batteryfactory",
    "name": "Energy Storage",
    "description": "Research Energy Storage and build a Battery Factory for power storage solutions.",
    "icon": "game-icons:battery-75",
  },
  {
    "id": "t2_enginefactory",
    "name": "Mechanical Heart",
    "description": "Research Mechanical Engineering and build an Engine Factory.",
    "icon": "game-icons:gear-stick",
  },
  {
    "id": "t2_nuclear",
    "name": "Nuclear Age",
    "description": "Research Nuclear Power and build a Nuclear Reactor for massive energy.",
    "icon": "game-icons:nuclear",
  },
  {
    "id": "t2_hire_workers",
    "name": "Workforce",
    "description": "Hire workers to boost your factory efficiency.",
    "icon": "game-icons:overhead",
  },
  {
    "id": "t2_transport5",
    "name": "Logistics Network",
    "description": "Build 5 transport lines to create a proper supply chain.",
    "icon": "game-icons:truck",
  },
  {
    "id": "t2_produce_circuit",
    "name": "Circuit Board Milestone",
    "description": "Produce 25 circuit boards in your factory.",
    "icon": "game-icons:circuitry",
  },
  {
    "id": "t2_contract3",
    "name": "Reliable Partner",
    "description": "Complete 3 contracts to establish your reputation.",
    "icon": "game-icons:scroll-unfurled",
  },
  {
    "id": "t2_earn_50k",
    "name": "Profit Margin",
    "description": "Earn $50,000 total to expand operations.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t2_aluminium",
    "name": "Light Metal",
    "description": "Build a Bauxite Mine and Aluminium Factory for lightweight manufacturing.",
    "icon": "game-icons:metal-disc",
  },
  {
    "id": "t2_silicon_refinery",
    "name": "Silicon Valley Expansion",
    "description": "Research Electronics and build a Silicon Refinery for silicon wafers.",
    "icon": "game-icons:processor",
  },
  {
    "id": "t2_copper_refinery",
    "name": "Pure Copper",
    "description": "Research Electronics and build a Copper Refinery for copper ingots.",
    "icon": "game-icons:metal-scales",
  },
  {
    "id": "t2_titanium_refinery",
    "name": "Titanium Strength",
    "description": "Research Advanced Metallurgy and build a Titanium Refinery for rare earth processing.",
    "icon": "game-icons:shield-impact",
  },
  {
    "id": "t2_coolant_plant",
    "name": "Cool Running",
    "description": "Build a Coolant Plant to produce industrial coolant from water and oil.",
    "icon": "game-icons:snowflake-2",
  },
  {
    "id": "t2_optics_lab",
    "name": "Light Speed",
    "description": "Research Electronics and build an Optics Lab for fiber optics.",
    "icon": "game-icons:laser-burst",
  },
  {
    "id": "t2_solar_cell",
    "name": "Sun Power",
    "description": "Research Energy Storage and build a Solar Cell Factory.",
    "icon": "game-icons:solar-power",
  },
  {
    "id": "t2_display_factory",
    "name": "Screen Time",
    "description": "Research Electronics and build a Display Factory for display panels.",
    "icon": "game-icons:tv",
  },
  {
    "id": "t2_hydrogen_plant",
    "name": "Hydrogen Economy",
    "description": "Research Energy Storage and build a Hydrogen Plant for hydrogen fuel.",
    "icon": "game-icons:h2o",
  },
  {
    "id": "t2_insecticide",
    "name": "Pest Control",
    "description": "Research Basic Machining and build an Insecticide Factory.",
    "icon": "game-icons:poison",
  },
  {
    "id": "t2_quarry",
    "name": "Quarry Operations",
    "description": "Build a Sand Mine to extract sand for glass and silicon production.",
    "icon": "game-icons:desert",
  },
  {
    "id": "t2_wolframite_mine",
    "name": "Tungsten Source",
    "description": "Research Advanced Metallurgy and build a Wolframite Mine for tungsten production.",
    "icon": "game-icons:obelisk",
  },
  {
    "id": "t2_produce_gear",
    "name": "Gear Milestone",
    "description": "Produce 20 gears in your gear factory.",
    "icon": "game-icons:big-gear",
  },
  {
    "id": "t2_produce_silicon",
    "name": "Silicon Milestone",
    "description": "Produce 15 silicon in your silicon refinery.",
    "icon": "game-icons:processor",
  },
  {
    "id": "t2_produce_aluminium",
    "name": "Aluminium Milestone",
    "description": "Produce 15 aluminium in your aluminium factory.",
    "icon": "game-icons:metal-disc",
  },
  {
    "id": "t2_produce_coolant",
    "name": "Coolant Milestone",
    "description": "Produce 25 coolant in your coolant plant.",
    "icon": "game-icons:snowflake-2",
  },
  {
    "id": "t2_produce_fiberoptics",
    "name": "Fiber Optics Milestone",
    "description": "Produce 15 fiber optics in your optics lab.",
    "icon": "game-icons:laser-burst",
  },
  {
    "id": "t2_produce_solarcell",
    "name": "Solar Cell Milestone",
    "description": "Produce 10 solar cells in your solar cell factory.",
    "icon": "game-icons:solar-power",
  },
  {
    "id": "t2_produce_copperingot",
    "name": "Copper Ingot Milestone",
    "description": "Produce 20 copper ingots in your copper refinery.",
    "icon": "game-icons:gold-bar",
  },
  {
    "id": "t2_produce_insecticide",
    "name": "Insecticide Milestone",
    "description": "Produce 15 insecticide in your insecticide factory.",
    "icon": "game-icons:poison",
  },
  {
    "id": "t3_ailab",
    "name": "Artificial Minds",
    "description": "Research Artificial Intelligence and build an AI Lab.",
    "icon": "game-icons:brain",
  },
  {
    "id": "t3_robotics",
    "name": "Rise of Machines",
    "description": "Research Robotics Tech and build a Robotics Bay to assemble robotic units.",
    "icon": "game-icons:robot-grab",
  },
  {
    "id": "t3_quantum",
    "name": "Quantum Leap",
    "description": "Research Quantum Physics and build a Quantum Lab.",
    "icon": "game-icons:atom",
  },
  {
    "id": "t3_electronics",
    "name": "Electronics Age",
    "description": "Build an Electronics Factory to assemble advanced electronics from circuits and silicon.",
    "icon": "game-icons:smartphone",
  },
  {
    "id": "t3_alloy",
    "name": "Advanced Metallurgy",
    "description": "Research Advanced Metallurgy and build an Alloy Forge for advanced alloys.",
    "icon": "game-icons:metal-bar",
  },
  {
    "id": "t3_fusion",
    "name": "Fusion Power",
    "description": "Research Fusion Energy and build a Fusion Reactor — the pinnacle of clean energy.",
    "icon": "game-icons:reactor",
  },
  {
    "id": "t3_megaproject",
    "name": "Mega Aspirations",
    "description": "Start a Mega Project and make progress toward completion.",
    "icon": "game-icons:castle",
  },
  {
    "id": "t3_efficiency",
    "name": "Peak Performance",
    "description": "Achieve 90%+ power efficiency across your factory.",
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "t3_produce_aichip",
    "name": "AI Chip Milestone",
    "description": "Produce 10 AI chips in your labs.",
    "icon": "game-icons:brain",
  },
  {
    "id": "t3_transport10",
    "name": "Supply Chain Master",
    "description": "Build 10 transport lines and connect your entire factory network.",
    "icon": "game-icons:steam-locomotive",
  },
  {
    "id": "t3_contract5",
    "name": "Corporate Contractor",
    "description": "Complete 5 contracts to become a trusted corporate supplier.",
    "icon": "game-icons:scroll-unfurled",
  },
  {
    "id": "t3_earn_500k",
    "name": "Half Million",
    "description": "Earn $500,000 total to become a major industrial power.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t3_nanola",
    "name": "Nano Scale",
    "description": "Research Nanotechnology and build a Nano Lab — the ultimate production facility.",
    "icon": "game-icons:nano-bot",
  },
  {
    "id": "t3_medtech",
    "name": "Medical Revolution",
    "description": "Research Advanced Metallurgy and build a Medical Tech Lab for life-saving technology.",
    "icon": "game-icons:hospital-cross",
  },
  {
    "id": "t3_goldsmith",
    "name": "Jewel Crafter",
    "description": "Research Nanotechnology and build a Goldsmith for precious jewellery production.",
    "icon": "game-icons:diamond-ring",
  },
  {
    "id": "t3_tungsten",
    "name": "Tungsten Titan",
    "description": "Research Advanced Metallurgy and build a Tungsten Smelter for tungsten production.",
    "icon": "game-icons:iron-cross",
  },
  {
    "id": "t3_arms",
    "name": "Arms Manufacturer",
    "description": "Research Mechanical Engineering and build an Arms Factory for weapons production.",
    "icon": "game-icons:ak47",
  },
  {
    "id": "t3_drone_shipyard",
    "name": "Drone Commander",
    "description": "Research Robotics Tech and build a Drone Shipyard for scan drone production.",
    "icon": "game-icons:space-shuttle",
  },
  {
    "id": "t3_detector",
    "name": "Artifact Hunter",
    "description": "Research Quantum Physics and build a Detector Factory for artifact detectors.",
    "icon": "game-icons:satellite",
  },
  {
    "id": "t3_neural",
    "name": "Neural Network",
    "description": "Research Artificial Intelligence and build a Neural Lab for neural network construction.",
    "icon": "game-icons:thought-bubble",
  },
  {
    "id": "t3_produce_advancedalloy",
    "name": "Advanced Alloy Milestone",
    "description": "Produce 10 advanced alloys in your alloy forge.",
    "icon": "game-icons:metal-bar",
  },
  {
    "id": "t3_produce_nanomaterial",
    "name": "Nano Material Milestone",
    "description": "Produce 5 nano materials in your nano lab.",
    "icon": "game-icons:nano-bot",
  },
  {
    "id": "t3_produce_medicaltech",
    "name": "Medical Tech Milestone",
    "description": "Produce 5 medical tech in your medical tech lab.",
    "icon": "game-icons:hospital-cross",
  },
  {
    "id": "t3_produce_jewellery",
    "name": "Jewellery Milestone",
    "description": "Produce 3 jewellery in your goldsmith.",
    "icon": "game-icons:diamond-ring",
  },
  {
    "id": "t3_produce_tungsten",
    "name": "Tungsten Milestone",
    "description": "Produce 10 tungsten in your tungsten smelter.",
    "icon": "game-icons:iron-cross",
  },
  {
    "id": "t3_produce_weapons",
    "name": "Weapons Milestone",
    "description": "Produce 5 weapons in your arms factory.",
    "icon": "game-icons:ak47",
  },
  {
    "id": "t3_produce_scandrone",
    "name": "Scan Drone Milestone",
    "description": "Produce 3 scan drones in your drone shipyard.",
    "icon": "game-icons:space-shuttle",
  },
  {
    "id": "t3_produce_artifactdetector",
    "name": "Artifact Detector Milestone",
    "description": "Produce 2 artifact detectors in your detector factory.",
    "icon": "game-icons:satellite",
  },
  {
    "id": "t3_produce_neuralnetwork",
    "name": "Neural Network Milestone",
    "description": "Produce 5 neural networks in your neural lab.",
    "icon": "game-icons:thought-bubble",
  },
  {
    "id": "t3_produce_quantumpart",
    "name": "Quantum Part Milestone",
    "description": "Produce 5 quantum parts in your quantum lab.",
    "icon": "game-icons:atom",
  },
  {
    "id": "t3_research15",
    "name": "Research Master",
    "description": "Complete 15 research projects to master the technology tree.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "t3_earn_2m",
    "name": "Two Million Club",
    "description": "Earn $2,000,000 total — an industrial powerhouse.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t4_singularity",
    "name": "The Singularity",
    "description": "Research Singularity Theory and build a Singularity Forge — the ultimate production facility.",
    "icon": "game-icons:vortex",
  },
  {
    "id": "t4_darkmatter",
    "name": "Dark Matter Discovery",
    "description": "Research Void Crystallography and build a Dark Matter Lab.",
    "icon": "game-icons:hole",
  },
  {
    "id": "t4_warp",
    "name": "Faster Than Light",
    "description": "Research Warp Technology and build a Warp Drive Factory.",
    "icon": "game-icons:rocket-thruster",
  },
  {
    "id": "t4_antimatter",
    "name": "Antimatter Revolution",
    "description": "Research Antimatter Physics and build an Antimatter Reactor.",
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "t4_chrono",
    "name": "Time Bender",
    "description": "Research Chrono Engineering and build a Chrono Lab to manipulate time itself.",
    "icon": "game-icons:hourglass",
  },
  {
    "id": "t4_plasma",
    "name": "Plasma Master",
    "description": "Research Plasma Dynamics and build a Plasma Forge.",
    "icon": "game-icons:flame-tunnel",
  },
  {
    "id": "t4_void_crystal",
    "name": "Void Crystal Harvest",
    "description": "Build a Void Crystallizer to harvest void energy from quantum parts and nano materials.",
    "icon": "game-icons:implosion",
  },
  {
    "id": "t4_megastructure",
    "name": "Mega Builder",
    "description": "Build a Mega Structure Factory to construct massive modules from concrete, steel, and advanced alloys.",
    "icon": "game-icons:castle",
  },
  {
    "id": "t4_dyson",
    "name": "Stellar Harvester",
    "description": "Build a Dyson Collector to harvest stellar energy — requires Dimensional Physics research and 2 prestiges.",
    "icon": "game-icons:solar-system",
  },
  {
    "id": "t4_galactic_forge",
    "name": "Galactic Forge",
    "description": "Build the ultimate Galactic Forge — converts T4 resources into immeasurable wealth. Requires 5 prestiges.",
    "icon": "game-icons:galaxy",
  },
  {
    "id": "t4_produce_singularity",
    "name": "Singularity Core Milestone",
    "description": "Produce 5 Singularity Cores — the key to transcending ordinary physics.",
    "icon": "game-icons:vortex",
  },
  {
    "id": "t4_earn_5m",
    "name": "Multi-Millionaire",
    "description": "Earn $5,000,000 total — a true industrial empire.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t4_research_all",
    "name": "Complete Knowledge",
    "description": "Complete 10 research projects to unlock the full technology tree.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "t4_prestige",
    "name": "Global Expansion",
    "description": "Prestige to expand your corporation globally and unlock permanent bonuses.",
    "icon": "game-icons:crystal-growth",
  },
  {
    "id": "t4_antimatter_power",
    "name": "Antimatter Power",
    "description": "Build an Antimatter Power Plant — the ultimate energy source producing 1000 MW.",
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "t4_quantum_teleporter",
    "name": "Quantum Teleportation",
    "description": "Research Dimensional Physics and prestige 2 times, then build a Quantum Teleporter.",
    "icon": "game-icons:teleport",
  },
  {
    "id": "t4_dimensional_gateway",
    "name": "Dimensional Rift",
    "description": "Research Dimensional Physics and prestige 3 times, then build a Dimensional Gateway.",
    "icon": "game-icons:portal",
  },
  {
    "id": "t4_time_distorter",
    "name": "Time Bender Supreme",
    "description": "Research Galactic Manufacturing and prestige 3 times, then build a Time Distorter.",
    "icon": "game-icons:hourglass",
  },
  {
    "id": "t4_produce_darkmatter",
    "name": "Dark Matter Cell Milestone",
    "description": "Produce 3 dark matter cells — harness the void.",
    "icon": "game-icons:hole",
  },
  {
    "id": "t4_produce_warpdrive",
    "name": "Warp Drive Milestone",
    "description": "Produce 2 warp drives — bend spacetime.",
    "icon": "game-icons:rocket-thruster",
  },
  {
    "id": "t4_produce_antimatter",
    "name": "Antimatter Milestone",
    "description": "Produce 5 antimatter — the ultimate energy source.",
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "t4_produce_chronopart",
    "name": "Chrono Part Milestone",
    "description": "Produce 3 chrono parts — manipulate time.",
    "icon": "game-icons:hourglass",
  },
  {
    "id": "t4_produce_plasmacore",
    "name": "Plasma Core Milestone",
    "description": "Produce 5 plasma cores — harness superheated plasma.",
    "icon": "game-icons:flame-tunnel",
  },
  {
    "id": "t4_produce_megastructure",
    "name": "Mega Structure Milestone",
    "description": "Produce 3 mega structures — build on an unprecedented scale.",
    "icon": "game-icons:castle",
  },
  {
    "id": "t4_produce_voidcrystal",
    "name": "Void Crystal Milestone",
    "description": "Produce 3 void crystals — study the void.",
    "icon": "game-icons:implosion",
  },
  {
    "id": "t4_prestige_3",
    "name": "Triple Expansion",
    "description": "Prestige 3 times to expand your corporation across multiple dimensions.",
    "icon": "game-icons:crystal-growth",
  },
  {
    "id": "t4_research_all_complete",
    "name": "Complete All Research",
    "description": "Complete all 26 research projects to achieve total technological supremacy.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "t4_earn_50m",
    "name": "Fifty Million",
    "description": "Earn $50,000,000 total — the ultimate industrial empire.",
    "icon": "game-icons:coins",
  },
  {
    "id": "t4_build_50",
    "name": "Build 50 Buildings",
    "description": "Build 50 buildings total — an empire spanning the globe.",
    "icon": "game-icons:castle",
  },
  {
    "id": "t4_contract_20",
    "name": "Contract Veteran",
    "description": "Complete 20 contracts — the most trusted supplier in the galaxy.",
    "icon": "game-icons:scroll-unfurled",
  },
  {
    "id": "daily_build",
    "name": "Daily Builder",
    "description": "Build 3 new buildings today to expand your empire.",
    "icon": "game-icons:factory",
  },
  {
    "id": "daily_earn",
    "name": "Daily Earnings",
    "description": "Earn $5,000 from sales today.",
    "icon": "game-icons:coins",
  },
  {
    "id": "daily_sell",
    "name": "Daily Trader",
    "description": "Sell 10 resources on the market today.",
    "icon": "game-icons:shop",
  },
  {
    "id": "daily_contract",
    "name": "Daily Contract",
    "description": "Complete 1 contract today to maintain your reputation.",
    "icon": "game-icons:scroll-unfurled",
  },
  {
    "id": "daily_research",
    "name": "Daily Researcher",
    "description": "Complete 1 research project today to advance your technology.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "daily_produce",
    "name": "Daily Producer",
    "description": "Produce 100 resources total today across all factories.",
    "icon": "game-icons:wooden-crate",
  },
  {
    "id": "daily_power",
    "name": "Daily Power Manager",
    "description": "Keep your power efficiency above 80% today — maintain optimal grid performance.",
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "weekly_industrialist",
    "name": "Weekly Industrialist",
    "description": "A week of expansion: build 10 buildings, complete 3 contracts, and earn $50,000.",
    "icon": "game-icons:factory",
  },
  {
    "id": "weekly_researcher",
    "name": "Weekly Scholar",
    "description": "Complete 3 research projects and produce 50 advanced resources this week.",
    "icon": "game-icons:erlenmeyer",
  },
  {
    "id": "weekly_transport",
    "name": "Weekly Logistics",
    "description": "Build 8 transport lines and connect all your active buildings this week.",
    "icon": "game-icons:truck",
  },
  {
    "id": "weekly_mega",
    "name": "Weekly Mega Builder",
    "description": "Build T3+ factories, reach high efficiency, and make progress on a Mega Project.",
    "icon": "game-icons:castle",
  },
  {
    "id": "weekly_singularity",
    "name": "Weekly Singularity",
    "description": "Produce T4 resources, complete research, and earn massive profits.",
    "icon": "game-icons:galaxy",
  },
  {
    "id": "weekly_arms_dealer",
    "name": "Weekly Arms Dealer",
    "description": "Produce T3 weapons and defense resources: weapons, scan drones, and advanced alloys.",
    "icon": "game-icons:ak47",
  },
  {
    "id": "weekly_void_explorer",
    "name": "Weekly Void Explorer",
    "description": "Produce T4 resources and complete endgame activities: dark matter, void crystals, and galactic manufacturing.",
    "icon": "game-icons:galaxy",
  }
];

