// ============================================
// IndustryaX: UI Catalog — Research
// Static presentation metadata only (no game-logic Master fields).
// Split from uiCatalog.ts — behavior-identical data move.
// ============================================

export type ResearchUIMeta = {
  id: string;
  name: string;
  description: string;
  category: string;
  tier: number;
  icon: string;
};

export const RESEARCH_UI: ResearchUIMeta[] = [
  {
    "id": "basicAutomation",
    "name": "Basic Automation",
    "description": "+15% production speed for all extractors",
    "category": "automation",
    "tier": 1,
    "icon": "game-icons:gear-hammer",
  },
  {
    "id": "advancedAutomation",
    "name": "Advanced Automation",
    "description": "+25% production speed for all factories",
    "category": "automation",
    "tier": 2,
    "icon": "game-icons:mechanical-arm",
  },
  {
    "id": "basicMachining",
    "name": "Basic Machining",
    "description": "Unlocks Gear Factory",
    "category": "automation",
    "tier": 1,
    "icon": "game-icons:gear-hammer",
  },
  {
    "id": "sandExtraction",
    "name": "Sand Extraction",
    "description": "Unlocks Sand Mine — extract sand for glass and silicon production",
    "category": "automation",
    "tier": 1,
    "icon": "game-icons:desert",
  },
  {
    "id": "bauxiteExtraction",
    "name": "Bauxite Extraction",
    "description": "Unlocks Bauxite Mine — mine bauxite ore for aluminium production",
    "category": "automation",
    "tier": 1,
    "icon": "game-icons:mining-helmet",
  },
  {
    "id": "lithiumExtraction",
    "name": "Lithium Extraction",
    "description": "Unlocks Lithium Mine — mine lithium for battery and advanced tech",
    "category": "energy",
    "tier": 1,
    "icon": "game-icons:crystal-cluster",
  },
  {
    "id": "logistics1",
    "name": "Efficient Transport",
    "description": "+20% transport throughput for all lines",
    "category": "logistics",
    "tier": 1,
    "icon": "game-icons:truck",
  },
  {
    "id": "advancedLogistics",
    "name": "Advanced Logistics",
    "description": "+30% transport throughput, unlock Cargo Train",
    "category": "logistics",
    "tier": 2,
    "icon": "game-icons:steam-locomotive",
  },
  {
    "id": "energyEfficiency",
    "name": "Energy Efficiency",
    "description": "-15% power consumption for all buildings",
    "category": "energy",
    "tier": 1,
    "icon": "game-icons:lightning-storm",
  },
  {
    "id": "nuclearPower",
    "name": "Nuclear Power",
    "description": "Unlocks Nuclear Reactor",
    "category": "energy",
    "tier": 2,
    "icon": "game-icons:nuclear",
  },
  {
    "id": "fusionEnergy",
    "name": "Fusion Energy",
    "description": "Unlocks Fusion Reactor - limitless clean power",
    "category": "energy",
    "tier": 3,
    "icon": "game-icons:reactor",
  },
  {
    "id": "electronics",
    "name": "Electronics",
    "description": "Unlocks Circuit Factory",
    "category": "ai",
    "tier": 1,
    "icon": "game-icons:circuitry",
  },
  {
    "id": "energyStorage",
    "name": "Energy Storage",
    "description": "Unlocks Battery Factory",
    "category": "ai",
    "tier": 2,
    "icon": "game-icons:battery-75",
  },
  {
    "id": "artificialIntelligence",
    "name": "Artificial Intelligence",
    "description": "Unlocks AI Lab - the heart of advanced technology",
    "category": "ai",
    "tier": 2,
    "icon": "game-icons:brain",
  },
  {
    "id": "mechanicalEngineering",
    "name": "Mechanical Engineering",
    "description": "Unlocks Engine Factory",
    "category": "robotics",
    "tier": 1,
    "icon": "game-icons:wrench",
  },
  {
    "id": "roboticsTech",
    "name": "Robotics Technology",
    "description": "Unlocks Robotics Bay",
    "category": "robotics",
    "tier": 2,
    "icon": "game-icons:robot-grab",
  },
  {
    "id": "advancedMetallurgy",
    "name": "Advanced Metallurgy",
    "description": "Unlocks Alloy Forge",
    "category": "robotics",
    "tier": 2,
    "icon": "game-icons:metal-bar",
  },
  {
    "id": "advancedDrilling",
    "name": "Advanced Drilling",
    "description": "+20% extractor production speed",
    "category": "automation",
    "tier": 2,
    "icon": "game-icons:mining",
  },
  {
    "id": "efficientSmelting",
    "name": "Efficient Smelting",
    "description": "+15% T1 factory production speed",
    "category": "automation",
    "tier": 2,
    "icon": "game-icons:furnace",
  },
  {
    "id": "advancedElectronics",
    "name": "Advanced Electronics",
    "description": "+15% T2 factory production speed",
    "category": "ai",
    "tier": 2,
    "icon": "game-icons:processor",
  },
  {
    "id": "powerOptimization",
    "name": "Power Optimization",
    "description": "-10% power consumption for all factories",
    "category": "energy",
    "tier": 2,
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "cargoDrones",
    "name": "Cargo Drones",
    "description": "+25% transport throughput, unlock Drone transport",
    "category": "logistics",
    "tier": 2,
    "icon": "game-icons:ufo",
  },
  {
    "id": "quantumPhysics",
    "name": "Quantum Physics",
    "description": "Unlocks Quantum Lab",
    "category": "quantum",
    "tier": 3,
    "icon": "game-icons:atom",
  },
  {
    "id": "nanotechnology",
    "name": "Nanotechnology",
    "description": "Unlocks Nano Lab - the ultimate production facility",
    "category": "quantum",
    "tier": 3,
    "icon": "game-icons:nano-bot",
  },
  {
    "id": "marketAnalysis",
    "name": "Market Analysis",
    "description": "+20% better sell prices on the market",
    "category": "automation",
    "tier": 1,
    "icon": "game-icons:profit",
  },
  {
    "id": "workerTraining",
    "name": "Worker Training",
    "description": "+25% worker efficiency across all workers",
    "category": "automation",
    "tier": 2,
    "icon": "game-icons:overhead",
  },
  {
    "id": "storageExpansion",
    "name": "Storage Expansion",
    "description": "+50% resource storage capacity",
    "category": "logistics",
    "tier": 2,
    "icon": "game-icons:warehouse",
  },
  {
    "id": "aiOptimization",
    "name": "AI Optimization",
    "description": "+20% AI Lab and Neural Lab speed",
    "category": "ai",
    "tier": 3,
    "icon": "game-icons:brain",
  },
  {
    "id": "advancedRobotics",
    "name": "Advanced Robotics",
    "description": "+25% Robotics Bay and Drone Shipyard speed",
    "category": "robotics",
    "tier": 3,
    "icon": "game-icons:robot-golem",
  },
  {
    "id": "quantumComputing",
    "name": "Quantum Computing",
    "description": "+30% Quantum Lab speed",
    "category": "quantum",
    "tier": 3,
    "icon": "game-icons:cpu",
  },
  {
    "id": "metabolicEngineering",
    "name": "Metabolic Engineering",
    "description": "+20% all T3 factory production speed",
    "category": "automation",
    "tier": 3,
    "icon": "game-icons:dna1",
  },
  {
    "id": "megaStorage",
    "name": "Mega Storage",
    "description": "+100% storage capacity",
    "category": "logistics",
    "tier": 3,
    "icon": "game-icons:warehouse",
  },
  {
    "id": "singularityTheory",
    "name": "Singularity Theory",
    "description": "Unlocks Singularity Forge — the first step beyond known physics",
    "category": "quantum",
    "tier": 4,
    "icon": "game-icons:vortex",
  },
  {
    "id": "antimatterPhysics",
    "name": "Antimatter Physics",
    "description": "Unlocks Antimatter Reactor and Antimatter Power Plant",
    "category": "energy",
    "tier": 4,
    "icon": "game-icons:lightning-frequency",
  },
  {
    "id": "warpTechnology",
    "name": "Warp Technology",
    "description": "Unlocks Warp Drive Factory — bend spacetime for FTL travel",
    "category": "robotics",
    "tier": 4,
    "icon": "game-icons:rocket-thruster",
  },
  {
    "id": "plasmaDynamics",
    "name": "Plasma Dynamics",
    "description": "Unlocks Plasma Forge — harness superheated plasma",
    "category": "energy",
    "tier": 4,
    "icon": "game-icons:flame-tunnel",
  },
  {
    "id": "chronoEngineering",
    "name": "Chrono Engineering",
    "description": "Unlocks Chrono Lab — manipulate the flow of time",
    "category": "quantum",
    "tier": 4,
    "icon": "game-icons:hourglass",
  },
  {
    "id": "voidCrystallography",
    "name": "Void Crystallography",
    "description": "Unlocks Void Crystallizer and Dark Matter Lab — study the void",
    "category": "quantum",
    "tier": 4,
    "icon": "game-icons:implosion",
  },
  {
    "id": "megaConstruction",
    "name": "Mega Construction",
    "description": "Unlocks Mega Structure Factory — build on an unprecedented scale",
    "category": "robotics",
    "tier": 4,
    "icon": "game-icons:castle",
  },
  {
    "id": "dimensionalPhysics",
    "name": "Dimensional Physics",
    "description": "Unlocks Dyson Collector, Quantum Teleporter, and Dimensional Gateway",
    "category": "quantum",
    "tier": 4,
    "icon": "game-icons:portal",
  },
  {
    "id": "galacticManufacturing",
    "name": "Galactic Manufacturing",
    "description": "Unlocks Time Distorter and Galactic Forge — the pinnacle of industrial civilization",
    "category": "quantum",
    "tier": 4,
    "icon": "game-icons:galaxy",
  }
];

