// ============================================
// IndustryaX: UI Catalog — Resources
// Static presentation metadata only (no game-logic Master fields).
// Split from uiCatalog.ts — behavior-identical data move.
// ============================================

import type { ResourceType } from '../../shared/types/types';

export const RESOURCE_META: Record<
  ResourceType,
  { name: string; icon: string; tier: number; color: string }
> = {
  iron: {
    "name": "Iron Ore",
    "icon": "game-icons:mine-wagon",
    "tier": 0,
    "color": "#a0a0a0",
  },
  copper: {
    "name": "Copper Ore",
    "icon": "game-icons:ore",
    "tier": 0,
    "color": "#b87333",
  },
  coal: {
    "name": "Coal",
    "icon": "game-icons:coal-wagon",
    "tier": 0,
    "color": "#333333",
  },
  oil: {
    "name": "Crude Oil",
    "icon": "game-icons:oil-rig",
    "tier": 0,
    "color": "#1a1a2e",
  },
  sand: {
    "name": "Sand",
    "icon": "game-icons:desert",
    "tier": 0,
    "color": "#c2b280",
  },
  lithium: {
    "name": "Lithium",
    "icon": "game-icons:crystal-cluster",
    "tier": 0,
    "color": "#7b68ee",
  },
  water: {
    "name": "Water",
    "icon": "game-icons:water-drop",
    "tier": 0,
    "color": "#4488ff",
  },
  rareEarth: {
    "name": "Rare Earth",
    "icon": "game-icons:sparkles",
    "tier": 0,
    "color": "#9932cc",
  },
  clay: {
    "name": "Clay",
    "icon": "game-icons:brick-pile",
    "tier": 0,
    "color": "#c2855a",
  },
  limestone: {
    "name": "Limestone",
    "icon": "game-icons:stone-pile",
    "tier": 0,
    "color": "#d4c5a9",
  },
  gravel: {
    "name": "Gravel",
    "icon": "game-icons:stone-block",
    "tier": 0,
    "color": "#8b8b8b",
  },
  bauxite: {
    "name": "Bauxite",
    "icon": "game-icons:peaks",
    "tier": 0,
    "color": "#cd853f",
  },
  wolframite: {
    "name": "Wolframite",
    "icon": "game-icons:dark-squad",
    "tier": 0,
    "color": "#4a4a4a",
  },
  silver: {
    "name": "Silver",
    "icon": "game-icons:metal-disc",
    "tier": 0,
    "color": "#c0c0c0",
  },
  gold: {
    "name": "Gold",
    "icon": "game-icons:gold-bar",
    "tier": 0,
    "color": "#ffd700",
  },
  ironPlate: {
    "name": "Iron Plate",
    "icon": "game-icons:metal-plate",
    "tier": 1,
    "color": "#c0c0c0",
  },
  copperWire: {
    "name": "Copper Wire",
    "icon": "game-icons:electric",
    "tier": 1,
    "color": "#daa520",
  },
  plastic: {
    "name": "Plastic",
    "icon": "game-icons:plastic-duck",
    "tier": 1,
    "color": "#ff6b6b",
  },
  glass: {
    "name": "Glass",
    "icon": "game-icons:glass-celebration",
    "tier": 1,
    "color": "#87ceeb",
  },
  carbon: {
    "name": "Carbon Fiber",
    "icon": "game-icons:coal-pile",
    "tier": 1,
    "color": "#2d2d2d",
  },
  bricks: {
    "name": "Bricks",
    "icon": "game-icons:brick-wall",
    "tier": 1,
    "color": "#b5533a",
  },
  concrete: {
    "name": "Concrete",
    "icon": "game-icons:concrete-bag",
    "tier": 1,
    "color": "#95a5a6",
  },
  fertilizer: {
    "name": "Fertilizer",
    "icon": "game-icons:fertilizer-bag",
    "tier": 1,
    "color": "#7cb342",
  },
  steel: {
    "name": "Steel",
    "icon": "game-icons:steel-claws",
    "tier": 1,
    "color": "#708090",
  },
  fossilFuel: {
    "name": "Fossil Fuel",
    "icon": "game-icons:fuel-tank",
    "tier": 1,
    "color": "#3e2723",
  },
  circuit: {
    "name": "Circuit Board",
    "icon": "game-icons:circuitry",
    "tier": 2,
    "color": "#00cc66",
  },
  engine: {
    "name": "Engine",
    "icon": "game-icons:gear-stick",
    "tier": 2,
    "color": "#ff8c00",
  },
  battery: {
    "name": "Battery",
    "icon": "game-icons:battery-75",
    "tier": 2,
    "color": "#32cd32",
  },
  gear: {
    "name": "Gear",
    "icon": "game-icons:big-gear",
    "tier": 2,
    "color": "#808080",
  },
  silicon: {
    "name": "Silicon",
    "icon": "game-icons:processor",
    "tier": 2,
    "color": "#8db4e2",
  },
  aluminium: {
    "name": "Aluminium",
    "icon": "game-icons:metal-disc",
    "tier": 2,
    "color": "#c0c0c0",
  },
  insecticide: {
    "name": "Insecticide",
    "icon": "game-icons:poison",
    "tier": 2,
    "color": "#76ff03",
  },
  copperIngot: {
    "name": "Copper Ingot",
    "icon": "game-icons:gold-bar",
    "tier": 2,
    "color": "#e67e22",
  },
  titanium: {
    "name": "Titanium",
    "icon": "game-icons:shield-impact",
    "tier": 2,
    "color": "#778899",
  },
  coolant: {
    "name": "Coolant",
    "icon": "game-icons:snowflake-2",
    "tier": 2,
    "color": "#00bfff",
  },
  fiberOptics: {
    "name": "Fiber Optics",
    "icon": "game-icons:laser-burst",
    "tier": 2,
    "color": "#f0e68c",
  },
  solarCell: {
    "name": "Solar Cell",
    "icon": "game-icons:solar-power",
    "tier": 2,
    "color": "#ffd700",
  },
  powerCell: {
    "name": "Power Cell",
    "icon": "game-icons:battery-100",
    "tier": 2,
    "color": "#00e676",
  },
  reinforcedConcrete: {
    "name": "Reinforced Concrete",
    "icon": "game-icons:concrete-bag",
    "tier": 2,
    "color": "#78909c",
  },
  refinedSilver: {
    "name": "Refined Silver",
    "icon": "game-icons:metal-disc",
    "tier": 2,
    "color": "#e0e0e0",
  },
  refinedGold: {
    "name": "Refined Gold",
    "icon": "game-icons:gold-bar",
    "tier": 2,
    "color": "#ffb300",
  },
  aiChip: {
    "name": "AI Chip",
    "icon": "game-icons:brain",
    "tier": 3,
    "color": "#00ffff",
  },
  robotics: {
    "name": "Robotics",
    "icon": "game-icons:robot-grab",
    "tier": 3,
    "color": "#ff69b4",
  },
  quantumPart: {
    "name": "Quantum Part",
    "icon": "game-icons:atom",
    "tier": 3,
    "color": "#9400d3",
  },
  advancedAlloy: {
    "name": "Adv. Alloy",
    "icon": "game-icons:metal-bar",
    "tier": 3,
    "color": "#4169e1",
  },
  nanoMaterial: {
    "name": "Nano Material",
    "icon": "game-icons:nano-bot",
    "tier": 3,
    "color": "#ff1493",
  },
  electronics: {
    "name": "Electronics",
    "icon": "game-icons:smartphone",
    "tier": 3,
    "color": "#00cc66",
  },
  medicalTech: {
    "name": "Medical Tech",
    "icon": "game-icons:hospital-cross",
    "tier": 3,
    "color": "#ff6b6b",
  },
  jewellery: {
    "name": "Jewellery",
    "icon": "game-icons:diamond-ring",
    "tier": 3,
    "color": "#e91e63",
  },
  tungsten: {
    "name": "Tungsten",
    "icon": "game-icons:iron-cross",
    "tier": 3,
    "color": "#5c5c5c",
  },
  weapons: {
    "name": "Weapons",
    "icon": "game-icons:ak47",
    "tier": 3,
    "color": "#b71c1c",
  },
  scanDrone: {
    "name": "Scan Drone",
    "icon": "game-icons:space-shuttle",
    "tier": 3,
    "color": "#00e5ff",
  },
  artifactDetector: {
    "name": "Artifact Detector",
    "icon": "game-icons:satellite",
    "tier": 3,
    "color": "#ff6f00",
  },
  neuralNetwork: {
    "name": "Neural Network",
    "icon": "game-icons:thought-bubble",
    "tier": 3,
    "color": "#ff6347",
  },
  carbonComposite: {
    "name": "Carbon Composite",
    "icon": "game-icons:rope-coil",
    "tier": 3,
    "color": "#37474f",
  },
  structuralFrame: {
    "name": "Structural Frame",
    "icon": "game-icons:steel-claws",
    "tier": 3,
    "color": "#546e7a",
  },
  fusionCell: {
    "name": "Fusion Cell",
    "icon": "game-icons:nuclear-bomb",
    "tier": 3,
    "color": "#ffab00",
  },
  solarPanel: {
    "name": "Solar Panel",
    "icon": "game-icons:solar-power",
    "tier": 3,
    "color": "#ffc107",
  },
  creditChip: {
    "name": "Credit Chip",
    "icon": "game-icons:id-card",
    "tier": 3,
    "color": "#26a69a",
  },
  singularityCore: {
    "name": "Singularity Core",
    "icon": "game-icons:vortex",
    "tier": 4,
    "color": "#00ffcc",
  },
  darkMatterCell: {
    "name": "Dark Matter Cell",
    "icon": "game-icons:hole",
    "tier": 4,
    "color": "#1a0033",
  },
  warpDrive: {
    "name": "Warp Drive",
    "icon": "game-icons:rocket-thruster",
    "tier": 4,
    "color": "#ff4500",
  },
  antimatter: {
    "name": "Antimatter",
    "icon": "game-icons:lightning-frequency",
    "tier": 4,
    "color": "#ff00ff",
  },
  chronoPart: {
    "name": "Chrono Part",
    "icon": "game-icons:hourglass",
    "tier": 4,
    "color": "#ffd700",
  },
  plasmaCore: {
    "name": "Plasma Core",
    "icon": "game-icons:flame-tunnel",
    "tier": 4,
    "color": "#ff6600",
  },
  megaStructure: {
    "name": "Mega Structure",
    "icon": "game-icons:castle",
    "tier": 4,
    "color": "#4169e1",
  },
  voidCrystal: {
    "name": "Void Crystal",
    "icon": "game-icons:implosion",
    "tier": 4,
    "color": "#9400d3",
  },
  arcologyModule: {
    "name": "Arcology Module",
    "icon": "game-icons:modern-city",
    "tier": 4,
    "color": "#4fc3f7",
  },
  habitatModule: {
    "name": "Habitat Module",
    "icon": "game-icons:house",
    "tier": 4,
    "color": "#81c784",
  },
  stellarEnergy: {
    "name": "Stellar Energy",
    "icon": "game-icons:star-formation",
    "tier": 4,
    "color": "#fff176",
  },
  luxuryGoods: {
    "name": "Luxury Goods",
    "icon": "game-icons:crown",
    "tier": 4,
    "color": "#f48fb1",
  },
  tradeContract: {
    "name": "Trade Contract",
    "icon": "game-icons:scroll-unfurled",
    "tier": 4,
    "color": "#a5d6a7",
  },
  teleporterNode: {
    "name": "Teleporter Node",
    "icon": "game-icons:teleport",
    "tier": 4,
    "color": "#b39ddb",
  },
  researchMatrix: {
    "name": "Research Matrix",
    "icon": "game-icons:circuitry",
    "tier": 5,
    "color": "#00e5ff",
  },
  worldCore: {
    "name": "World Core",
    "icon": "game-icons:planet-core",
    "tier": 5,
    "color": "#ff6e40",
  },
  shieldMatrix: {
    "name": "Shield Matrix",
    "icon": "game-icons:round-shield",
    "tier": 5,
    "color": "#69f0ae",
  },
  stellarForge: {
    "name": "Stellar Forge",
    "icon": "game-icons:anvil-impact",
    "tier": 5,
    "color": "#ffd740",
  },
  voidEnergy: {
    "name": "Void Energy",
    "icon": "game-icons:hole",
    "tier": 5,
    "color": "#7c4dff",
  },
  marketDominance: {
    "name": "Market Dominance",
    "icon": "game-icons:crown",
    "tier": 5,
    "color": "#ff5252",
  },
  corpCapital: {
    "name": "Corp Capital",
    "icon": "game-icons:bank",
    "tier": 5,
    "color": "#448aff",
  },
  dimensionalGate: {
    "name": "Dimensional Gate",
    "icon": "game-icons:gate",
    "tier": 5,
    "color": "#e040fb",
  },
  armadaFleet: {
    "name": "Armada Fleet",
    "icon": "game-icons:spaceship",
    "tier": 5,
    "color": "#ff6d00",
  }
} as Record<ResourceType, { name: string; icon: string; tier: number; color: string }>;

