import type { GameState, ResourceType } from "@/lib/game/types";
import type { GameNotification } from "@/lib/game/types";
import {
  INITIAL_MARKET,
  AUTOMATION_UNLOCKS,
  PRESTIGE_BONUSES,
  QUEST_DEFS,
  INITIAL_MEGA_PROJECTS,
  SEASONAL_EVENTS,
} from "@/lib/game/configCache";
import { emptyProductionSnapshot } from "@/lib/game/productionCalculator";
import { generateId } from "@/lib/game/utils/generateId";

// --- Initial State ---
export const initialResources: Record<ResourceType, number> = {
  // T0 - Raw Resources
  iron: 0,
  copper: 0,
  coal: 0,
  oil: 0,
  sand: 0,
  lithium: 0,
  water: 0,
  clay: 0,
  limestone: 0,
  gravel: 0,
  bauxite: 0,
  wolframite: 0,
  silver: 0,
  gold: 0,
  // T1 - Basic Processed
  rareEarth: 0,
  ironPlate: 0,
  copperWire: 0,
  plastic: 0,
  glass: 0,
  carbon: 0,
  bricks: 0,
  concrete: 0,
  fertilizer: 0,
  steel: 0,
  fossilFuel: 0,
  // T2 - Intermediate
  circuit: 0,
  engine: 0,
  battery: 0,
  gear: 0,
  silicon: 0,
  aluminium: 0,
  insecticide: 0,
  copperIngot: 0,
  titanium: 0,
  coolant: 0,
  fiberOptics: 0,
  solarCell: 0,
  powerCell: 0,
  reinforcedConcrete: 0,
  refinedSilver: 0,
  refinedGold: 0,
  // T3 - Advanced
  aiChip: 0,
  robotics: 0,
  quantumPart: 0,
  advancedAlloy: 0,
  nanoMaterial: 0,
  electronics: 0,
  medicalTech: 0,
  jewellery: 0,
  tungsten: 0,
  weapons: 0,
  scanDrone: 0,
  artifactDetector: 0,
  neuralNetwork: 0,
  carbonComposite: 0,
  structuralFrame: 0,
  fusionCell: 0,
  solarPanel: 0,
  creditChip: 0,
  // T4 - Endgame
  singularityCore: 0,
  darkMatterCell: 0,
  warpDrive: 0,
  antimatter: 0,
  chronoPart: 0,
  plasmaCore: 0,
  megaStructure: 0,
  voidCrystal: 0,
  arcologyModule: 0,
  habitatModule: 0,
  stellarEnergy: 0,
  luxuryGoods: 0,
  tradeContract: 0,
  teleporterNode: 0,
  // T5 - Transcendent
  researchMatrix: 0,
  worldCore: 0,
  shieldMatrix: 0,
  stellarForge: 0,
  voidEnergy: 0,
  marketDominance: 0,
  corpCapital: 0,
  dimensionalGate: 0,
  armadaFleet: 0,
};

export const initialCapacity: Record<ResourceType, number> = {
  // T0 - Raw Resources
  iron: 100,
  copper: 100,
  coal: 100,
  oil: 100,
  sand: 100,
  lithium: 50,
  water: 200,
  clay: 500,
  limestone: 500,
  gravel: 500,
  bauxite: 200,
  wolframite: 100,
  silver: 100,
  gold: 100,
  // T1 - Basic Processed
  rareEarth: 20,
  ironPlate: 50,
  copperWire: 50,
  plastic: 50,
  glass: 50,
  carbon: 30,
  bricks: 200,
  concrete: 200,
  fertilizer: 200,
  steel: 40,
  fossilFuel: 200,
  // T2 - Intermediate
  circuit: 30,
  engine: 20,
  battery: 30,
  gear: 40,
  silicon: 100,
  aluminium: 100,
  insecticide: 100,
  copperIngot: 100,
  titanium: 100,
  coolant: 100,
  fiberOptics: 100,
  solarCell: 100,
  powerCell: 100,
  reinforcedConcrete: 200,
  refinedSilver: 50,
  refinedGold: 50,
  // T3 - Advanced
  aiChip: 10,
  robotics: 5,
  quantumPart: 5,
  advancedAlloy: 10,
  nanoMaterial: 3,
  electronics: 50,
  medicalTech: 50,
  jewellery: 25,
  tungsten: 50,
  weapons: 50,
  scanDrone: 25,
  artifactDetector: 25,
  neuralNetwork: 25,
  carbonComposite: 25,
  structuralFrame: 25,
  fusionCell: 25,
  solarPanel: 50,
  creditChip: 25,
  // T4 - Endgame
  singularityCore: 50,
  darkMatterCell: 50,
  warpDrive: 50,
  antimatter: 50,
  chronoPart: 50,
  plasmaCore: 50,
  megaStructure: 50,
  voidCrystal: 50,
  arcologyModule: 25,
  habitatModule: 25,
  stellarEnergy: 25,
  luxuryGoods: 25,
  tradeContract: 25,
  teleporterNode: 25,
  // T5 - Transcendent
  researchMatrix: 10,
  worldCore: 10,
  shieldMatrix: 10,
  stellarForge: 10,
  voidEnergy: 10,
  marketDominance: 10,
  corpCapital: 10,
  dimensionalGate: 10,
  armadaFleet: 10,
};

export function createInitialState(): GameState {
  return {
    money: 1000,
    totalMoneyEarned: 0,
    gameTick: 0,
    gameSpeed: 1,
    paused: false,
    resources: { ...initialResources },
    resourceCapacity: { ...initialCapacity },
    buildings: [],
    transportLines: [],
    powerGrid: {
      totalProduction: 0,
      totalConsumption: 0,
      efficiency: 1,
      overload: false,
      plants: [],
    },
    researchPoints: 0,
    completedResearch: [],
    activeResearch: null,
    researchProgress: 0,
    workers: [],
    market: INITIAL_MARKET.map((m) => ({ ...m })),
    sectorTrends: {},
    marketNews: [],
    marketNarratives: [],
    // Server-authoritative market data. Populated by useServerMarket polling /api/market/state
    // every 10s. Initialized to empty so the first render of MarketPanel doesn't crash on
    // undefined prices — see AUDIT_FIXES_2026_06_18.md P0-#4.
    serverMarket: {
      prices: [],
      news: [],
      tick: 0,
      volatility: 0,
    },
    contracts: [],
    completedContracts: 0,
    automationUnlocks: AUTOMATION_UNLOCKS.map((a) => ({ ...a })),
    prestigeState: {
      corporationPoints: 0,
      totalPrestiges: 0,
      megaFactoryUnlocked: false,
      bonuses: PRESTIGE_BONUSES.map((b) => ({ ...b })),
    },
    activeEvents: [],
    eventLog: [],
    stats: {
      totalResourcesProduced: { ...initialResources },
      totalResourcesSold: { ...initialResources },
      peakEfficiency: 0,
      factoriesBuilt: 0,
      transportLinesBuilt: 0,
      researchCompleted: 0,
      contractsCompleted: 0,
      playTime: 0,
    },
    megaProjects: INITIAL_MEGA_PROJECTS.map((p) => ({
      ...p,
      stages: p.stages.map((s) => ({ ...s })),
    })),
    productionHistory: [],
    blueprints: [],
    autoSellResources: [],
    storageUpgradeLevels: { ...initialResources },
    lastOnlineTimestamp: Date.now(),

    leaderboardEntries: [],
    loginStreak: {
      currentStreak: 0,
      longestStreak: 0,
      lastLoginDate: "",
      totalLogins: 0,
      weeklyRewards: [],
    },
    weather: {
      current: "clear" as const,
      intensity: 0,
      remaining: 0,
      nextChange: 100 + Math.floor(Math.random() * 200),
    },
    quests: QUEST_DEFS.map((q) => ({
      ...q,
      steps: q.steps.map((s) => ({ ...s })),
    })),
    payoutConfig: {
      basePayoutInterval: 100,
      lastPayoutTick: 0,
      totalPayoutsReceived: 0,
      autoCollect: true,
    },
    pendingPayout: 0,
    payoutHistory: [],
    trackedQuest: null,
    drones: {
      fleet: [
        {
          id: generateId(),
          status: "idle" as const,
          missionEndTick: 0,
          missionId: null,
          speedLevel: 1,
          capacityLevel: 1,
          fuelEfficiencyLevel: 1,
        },
      ],
      completedMissions: 0,
      totalEarned: 0,
    },
    activeTab: "dashboard",
    selectedBuilding: null,
    notifications: [],
    productionSnapshot: emptyProductionSnapshot(),
  };
}
