-- Stub migration: matches DB version 20260617183241 but no source file found.
-- This file was auto-generated by scripts/rename-migrations-to-timestamps.ps1
-- The migration was applied directly to the DB at some prior point.
-- Re-applying here would error, so we use a no-op.

DO $$ BEGIN
  RAISE NOTICE 'Stub migration: 20260617183241_apply_market_tick_rpc (no-op)';
END $$;

SELECT 1;
